// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package meldapi

import (
	"MeldAPI/pkg/utils"
	"fmt"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Property Meld Production Application
	"https://app.propertymeld.com/",
}

// HTTPClient provides an interface for suplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

type sdkConfiguration struct {
	DefaultClient  HTTPClient
	SecurityClient HTTPClient

	ServerURL         string
	ServerIndex       int
	Language          string
	OpenAPIDocVersion string
	SDKVersion        string
	GenVersion        string
}

func (c *sdkConfiguration) GetServerDetails() (string, map[string]string) {
	if c.ServerURL != "" {
		return c.ServerURL, nil
	}

	return ServerList[c.ServerIndex], nil
}

// MeldAPI - Property Meld API: An API to access data from your Property Meld Account.
type MeldAPI struct {
	Building        *building
	CheckToken      *checkToken
	Estimates       *estimates
	Expenditure     *expenditure
	Floor           *floor
	Invoice         *invoice
	ManagementAgent *managementAgent
	ManagerFile     *managerFile
	Meld            *meld
	Owner           *owner
	Ping            *ping
	Project         *project
	Property        *property
	PropertyGroup   *propertyGroup
	Resident        *resident
	ResidentFile    *residentFile
	Schema          *schema
	Unit            *unit
	Vendor          *vendor
	VendorFile      *vendorFile
	VendorInvite    *vendorInvite
	WorkLog         *workLog

	sdkConfiguration sdkConfiguration
}

type SDKOption func(*MeldAPI)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *MeldAPI) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *MeldAPI) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *MeldAPI) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *MeldAPI) {
		sdk.sdkConfiguration.DefaultClient = client
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *MeldAPI {
	sdk := &MeldAPI{
		sdkConfiguration: sdkConfiguration{
			Language:          "go",
			OpenAPIDocVersion: "0.0.1",
			SDKVersion:        "1.1.0",
			GenVersion:        "2.39.0",
		},
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.DefaultClient == nil {
		sdk.sdkConfiguration.DefaultClient = &http.Client{Timeout: 60 * time.Second}
	}
	if sdk.sdkConfiguration.SecurityClient == nil {
		sdk.sdkConfiguration.SecurityClient = sdk.sdkConfiguration.DefaultClient
	}

	sdk.Building = newBuilding(sdk.sdkConfiguration)

	sdk.CheckToken = newCheckToken(sdk.sdkConfiguration)

	sdk.Estimates = newEstimates(sdk.sdkConfiguration)

	sdk.Expenditure = newExpenditure(sdk.sdkConfiguration)

	sdk.Floor = newFloor(sdk.sdkConfiguration)

	sdk.Invoice = newInvoice(sdk.sdkConfiguration)

	sdk.ManagementAgent = newManagementAgent(sdk.sdkConfiguration)

	sdk.ManagerFile = newManagerFile(sdk.sdkConfiguration)

	sdk.Meld = newMeld(sdk.sdkConfiguration)

	sdk.Owner = newOwner(sdk.sdkConfiguration)

	sdk.Ping = newPing(sdk.sdkConfiguration)

	sdk.Project = newProject(sdk.sdkConfiguration)

	sdk.Property = newProperty(sdk.sdkConfiguration)

	sdk.PropertyGroup = newPropertyGroup(sdk.sdkConfiguration)

	sdk.Resident = newResident(sdk.sdkConfiguration)

	sdk.ResidentFile = newResidentFile(sdk.sdkConfiguration)

	sdk.Schema = newSchema(sdk.sdkConfiguration)

	sdk.Unit = newUnit(sdk.sdkConfiguration)

	sdk.Vendor = newVendor(sdk.sdkConfiguration)

	sdk.VendorFile = newVendorFile(sdk.sdkConfiguration)

	sdk.VendorInvite = newVendorInvite(sdk.sdkConfiguration)

	sdk.WorkLog = newWorkLog(sdk.sdkConfiguration)

	return sdk
}
