// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package meldapi

import (
	"MeldAPI/pkg/models/operations"
	"MeldAPI/pkg/utils"
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"
)

type schema struct {
	sdkConfiguration sdkConfiguration
}

func newSchema(sdkConfig sdkConfiguration) *schema {
	return &schema{
		sdkConfiguration: sdkConfig,
	}
}

// SchemaRetrieve - OpenApi3 schema for this API. Format can be selected via content negotiation.
//
// - YAML: application/vnd.oai.openapi
// - JSON: application/vnd.oai.openapi+json
func (s *schema) SchemaRetrieve(ctx context.Context, request operations.SchemaRetrieveRequest, security operations.SchemaRetrieveSecurity) (*operations.SchemaRetrieveResponse, error) {
	baseURL := utils.ReplaceParameters(s.sdkConfiguration.GetServerDetails())
	url := strings.TrimSuffix(baseURL, "/") + "/api/v0.0.1/schema/"

	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json;q=1, application/vnd.oai.openapi+json;q=0.8, application/yaml;q=0.5, application/vnd.oai.openapi;q=0")
	req.Header.Set("user-agent", fmt.Sprintf("speakeasy-sdk/%s %s %s %s", s.sdkConfiguration.Language, s.sdkConfiguration.SDKVersion, s.sdkConfiguration.GenVersion, s.sdkConfiguration.OpenAPIDocVersion))

	utils.PopulateHeaders(ctx, req, request)

	if err := utils.PopulateQueryParams(ctx, req, request, nil); err != nil {
		return nil, fmt.Errorf("error populating query params: %w", err)
	}

	client := utils.ConfigureSecurityClient(s.sdkConfiguration.DefaultClient, security)

	httpRes, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("error sending request: %w", err)
	}
	if httpRes == nil {
		return nil, fmt.Errorf("error sending request: no response")
	}

	rawBody, err := io.ReadAll(httpRes.Body)
	if err != nil {
		return nil, fmt.Errorf("error reading response body: %w", err)
	}
	httpRes.Body.Close()
	httpRes.Body = io.NopCloser(bytes.NewBuffer(rawBody))

	contentType := httpRes.Header.Get("Content-Type")

	res := &operations.SchemaRetrieveResponse{
		StatusCode:  httpRes.StatusCode,
		ContentType: contentType,
		RawResponse: httpRes,
	}
	switch {
	case httpRes.StatusCode == 200:
		switch {
		case utils.MatchContentType(contentType, `application/json`):
			var out map[string]interface{}
			if err := utils.UnmarshalJsonFromResponseBody(bytes.NewBuffer(rawBody), &out); err != nil {
				return nil, err
			}

			res.SchemaRetrieve200ApplicationJSONObject = out
		case utils.MatchContentType(contentType, `application/vnd.oai.openapi`):
			res.Body = rawBody
		case utils.MatchContentType(contentType, `application/yaml`):
			res.Body = rawBody
		case utils.MatchContentType(contentType, `application/vnd.oai.openapi+json`):
			var out map[string]interface{}
			if err := utils.UnmarshalJsonFromResponseBody(bytes.NewBuffer(rawBody), &out); err != nil {
				return nil, err
			}

			res.SchemaRetrieve200ApplicationVndOaiOpenapiPlusJSONObject = out
		}
	}

	return res, nil
}
