// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CheckTokenRetrieveSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CheckTokenRetrieveResponse struct {
	ContentType                                string
	StatusCode                                 int
	RawResponse                                *http.Response
	CheckTokenRetrieve200ApplicationJSONObject map[string]interface{}
}
