// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

type EstimatesListSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type EstimatesListEstimateStatus string

const (
	EstimatesListEstimateStatusEstimateApproved          EstimatesListEstimateStatus = "ESTIMATE_APPROVED"
	EstimatesListEstimateStatusEstimateClosed            EstimatesListEstimateStatus = "ESTIMATE_CLOSED"
	EstimatesListEstimateStatusEstimateInProgress        EstimatesListEstimateStatus = "ESTIMATE_IN_PROGRESS"
	EstimatesListEstimateStatusEstimateOwnerRejected     EstimatesListEstimateStatus = "ESTIMATE_OWNER_REJECTED"
	EstimatesListEstimateStatusEstimatePendingAcceptance EstimatesListEstimateStatus = "ESTIMATE_PENDING_ACCEPTANCE"
	EstimatesListEstimateStatusEstimatePendingApproval   EstimatesListEstimateStatus = "ESTIMATE_PENDING_APPROVAL"
	EstimatesListEstimateStatusEstimateSubmitted         EstimatesListEstimateStatus = "ESTIMATE_SUBMITTED"
	EstimatesListEstimateStatusEstimateVendorRejected    EstimatesListEstimateStatus = "ESTIMATE_VENDOR_REJECTED"
)

func (e EstimatesListEstimateStatus) ToPointer() *EstimatesListEstimateStatus {
	return &e
}

func (e *EstimatesListEstimateStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ESTIMATE_APPROVED":
		fallthrough
	case "ESTIMATE_CLOSED":
		fallthrough
	case "ESTIMATE_IN_PROGRESS":
		fallthrough
	case "ESTIMATE_OWNER_REJECTED":
		fallthrough
	case "ESTIMATE_PENDING_ACCEPTANCE":
		fallthrough
	case "ESTIMATE_PENDING_APPROVAL":
		fallthrough
	case "ESTIMATE_SUBMITTED":
		fallthrough
	case "ESTIMATE_VENDOR_REJECTED":
		*e = EstimatesListEstimateStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EstimatesListEstimateStatus: %v", v)
	}
}

type EstimatesListRequest struct {
	// The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
	XPmOrg         int64                         `header:"style=simple,explode=false,name=X-Pm-Org"`
	EstimateStatus []EstimatesListEstimateStatus `queryParam:"style=form,explode=true,name=estimate_status"`
	// Number of results to return per page.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The initial index from which to return the results.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Which field to use when ordering the results.
	Ordering *string `queryParam:"style=form,explode=true,name=ordering"`
}

type EstimatesListResponse struct {
	ContentType                         string
	PaginatedEstimateSerializerListList *shared.PaginatedEstimateSerializerListList
	StatusCode                          int
	RawResponse                         *http.Response
}
