// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type MeldRetrieveSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type MeldRetrieveRequest struct {
	// The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
	XPmOrg int64  `header:"style=simple,explode=false,name=X-Pm-Org"`
	ID     string `pathParam:"style=simple,explode=false,name=id"`
}

type MeldRetrieveResponse struct {
	ContentType          string
	MeldSerializerDetail *shared.MeldSerializerDetailOutput
	StatusCode           int
	RawResponse          *http.Response
}
