// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type OwnerPartialUpdateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type OwnerPartialUpdateRequest struct {
	PatchedOwnerInput *shared.PatchedOwnerInput `request:"mediaType=application/json"`
	ID                string                    `pathParam:"style=simple,explode=false,name=id"`
}

type OwnerPartialUpdateResponse struct {
	ContentType string
	Owner       *shared.Owner
	StatusCode  int
	RawResponse *http.Response
}
