// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type OwnerRetrieveSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type OwnerRetrieveRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type OwnerRetrieveResponse struct {
	ContentType string
	Owner       *shared.Owner
	StatusCode  int
	RawResponse *http.Response
}
