// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type OwnerListSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type OwnerListRequest struct {
	// Number of results to return per page.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The initial index from which to return the results.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Which field to use when ordering the results.
	Ordering *string `queryParam:"style=form,explode=true,name=ordering"`
}

type OwnerListResponse struct {
	ContentType        string
	PaginatedOwnerList *shared.PaginatedOwnerList
	StatusCode         int
	RawResponse        *http.Response
}
