// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PingRetrieveResponse struct {
	ContentType                          string
	StatusCode                           int
	RawResponse                          *http.Response
	PingRetrieve200ApplicationJSONObject map[string]interface{}
}
