// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type PropertyRetrieveSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PropertyRetrieveRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type PropertyRetrieveResponse struct {
	ContentType string
	Property    *shared.Property
	StatusCode  int
	RawResponse *http.Response
}
