// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type PropertyPartialUpdateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PropertyPartialUpdateRequest struct {
	PatchedPropertyInput *shared.PatchedPropertyInput `request:"mediaType=application/json"`
	ID                   string                       `pathParam:"style=simple,explode=false,name=id"`
}

type PropertyPartialUpdateResponse struct {
	ContentType string
	Property    *shared.Property
	StatusCode  int
	RawResponse *http.Response
}
