// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type PropertyUpdateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PropertyUpdateRequest struct {
	PropertyInput shared.PropertyInput `request:"mediaType=application/json"`
	ID            string               `pathParam:"style=simple,explode=false,name=id"`
}

type PropertyUpdateResponse struct {
	ContentType string
	Property    *shared.Property
	StatusCode  int
	RawResponse *http.Response
}
