// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type PropertyCreateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PropertyCreateResponse struct {
	ContentType string
	Property    *shared.Property
	StatusCode  int
	RawResponse *http.Response
}
