// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type ResidentPartialUpdateFormSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ResidentPartialUpdateFormRequest struct {
	PatchedResidentInput1 *shared.PatchedResidentInput1 `request:"mediaType=application/x-www-form-urlencoded"`
	ID                    string                        `pathParam:"style=simple,explode=false,name=id"`
}

type ResidentPartialUpdateFormResponse struct {
	ContentType string
	Resident    *shared.Resident
	StatusCode  int
	RawResponse *http.Response
}
