// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type ResidentUpdateMultipartSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ResidentUpdateMultipartRequest struct {
	ResidentInput1 shared.ResidentInput1 `request:"mediaType=multipart/form-data"`
	ID             string                `pathParam:"style=simple,explode=false,name=id"`
}

type ResidentUpdateMultipartResponse struct {
	ContentType string
	Resident    *shared.Resident
	StatusCode  int
	RawResponse *http.Response
}
