// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type ResidentListSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ResidentListRequest struct {
	// Number of results to return per page.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The initial index from which to return the results.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Which field to use when ordering the results.
	Ordering *string `queryParam:"style=form,explode=true,name=ordering"`
}

type ResidentListResponse struct {
	ContentType           string
	PaginatedResidentList *shared.PaginatedResidentList
	StatusCode            int
	RawResponse           *http.Response
}
