// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type ResidentCreateFormSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ResidentCreateFormResponse struct {
	ContentType string
	Resident    *shared.Resident
	StatusCode  int
	RawResponse *http.Response
}
