// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type ResidentUpdateJSONSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ResidentUpdateJSONRequest struct {
	ResidentInput shared.ResidentInput `request:"mediaType=application/json"`
	ID            string               `pathParam:"style=simple,explode=false,name=id"`
}

type ResidentUpdateJSONResponse struct {
	ContentType string
	Resident    *shared.Resident
	StatusCode  int
	RawResponse *http.Response
}
