// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type ResidentPartialUpdateJSONSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ResidentPartialUpdateJSONRequest struct {
	PatchedResidentInput *shared.PatchedResidentInput `request:"mediaType=application/json"`
	ID                   string                       `pathParam:"style=simple,explode=false,name=id"`
}

type ResidentPartialUpdateJSONResponse struct {
	ContentType string
	Resident    *shared.Resident
	StatusCode  int
	RawResponse *http.Response
}
