// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type UnitCreateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UnitCreateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	Unit        *shared.Unit
}
