// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type UnitRetrieveSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UnitRetrieveRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UnitRetrieveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	Unit        *shared.Unit
}
