// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type UnitPartialUpdateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UnitPartialUpdateRequest struct {
	PatchedUnitInput *shared.PatchedUnitInput `request:"mediaType=application/json"`
	ID               string                   `pathParam:"style=simple,explode=false,name=id"`
}

type UnitPartialUpdateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	Unit        *shared.Unit
}
