// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type UnitUpdateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type UnitUpdateRequest struct {
	UnitInput shared.UnitInput `request:"mediaType=application/json"`
	ID        string           `pathParam:"style=simple,explode=false,name=id"`
}

type UnitUpdateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	Unit        *shared.Unit
}
