// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type VendorInviteCreateSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type VendorInviteCreateRequest struct {
	VendorInvite shared.VendorInvite `request:"mediaType=application/json"`
	// The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
	XPmOrg int64 `header:"style=simple,explode=false,name=X-Pm-Org"`
}

type VendorInviteCreateResponse struct {
	ContentType  string
	StatusCode   int
	RawResponse  *http.Response
	VendorInvite *shared.VendorInvite
}
