// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"MeldAPI/pkg/models/shared"
	"net/http"
)

type VendorRetrieveSecurity struct {
	PMOAuth2Authentication string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type VendorRetrieveRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type VendorRetrieveResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	Vendor      *shared.Vendor
}
