// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Address struct {
	City           string  `json:"city"`
	Country        *string `json:"country,omitempty"`
	CountyProvince string  `json:"county_province"`
	Line1          string  `json:"line_1"`
	Line2          *string `json:"line_2,omitempty"`
	Line3          *string `json:"line_3,omitempty"`
	Postcode       string  `json:"postcode"`
}
