// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BaseUser struct {
	Email     *string `json:"email,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	ID        int64   `json:"id"`
	LastName  *string `json:"last_name,omitempty"`
}
