// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type BasePayment struct {
	Amount         string                 `json:"amount"`
	AmountRefunded *string                `json:"amount_refunded,omitempty"`
	CheckNo        *string                `json:"check_no,omitempty"`
	CreateBy       map[string]interface{} `json:"create_by,omitempty"`
	Created        time.Time              `json:"created"`
	ID             int64                  `json:"id"`
	Method         MethodEnum             `json:"method"`
	Notes          *string                `json:"notes,omitempty"`
	StripeChargeID *string                `json:"stripe_charge_id,omitempty"`
	UpdateBy       map[string]interface{} `json:"update_by,omitempty"`
	Updated        time.Time              `json:"updated"`
}
