// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type BlankEnum string

const (
	BlankEnumUnknown BlankEnum = ""
)

func (e BlankEnum) ToPointer() *BlankEnum {
	return &e
}

func (e *BlankEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		*e = BlankEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BlankEnum: %v", v)
	}
}
