// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type BuildingSerializerDetail struct {
	Created time.Time `json:"created"`
	ID      int64     `json:"id"`
	Number  string    `json:"number"`
	Prop    int64     `json:"prop"`
	Updated time.Time `json:"updated"`
}
