// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ClassificationEnum string

const (
	ClassificationEnumPublic       ClassificationEnum = "PUBLIC"
	ClassificationEnumPrivate      ClassificationEnum = "PRIVATE"
	ClassificationEnumConfidential ClassificationEnum = "CONFIDENTIAL"
)

func (e ClassificationEnum) ToPointer() *ClassificationEnum {
	return &e
}

func (e *ClassificationEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUBLIC":
		fallthrough
	case "PRIVATE":
		fallthrough
	case "CONFIDENTIAL":
		*e = ClassificationEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ClassificationEnum: %v", v)
	}
}
