// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Contact struct {
	// Home phone number. Must be in E.164 format, e.g. '+14155552671'.
	BusinessPhone    *string `json:"business_phone,omitempty"`
	BusinessPhoneExt *string `json:"business_phone_ext,omitempty"`
	// Home phone number. Must be in E.164 format, e.g. '+14155552671'.
	CellPhone    *string `json:"cell_phone,omitempty"`
	CellPhoneExt *string `json:"cell_phone_ext,omitempty"`
	Fax          *string `json:"fax,omitempty"`
	// Home phone number. Must be in E.164 format, e.g. '+14155552671'.
	HomePhone      *string `json:"home_phone,omitempty"`
	HomePhoneExt   *string `json:"home_phone_ext,omitempty"`
	PrimaryEmail   *string `json:"primary_email,omitempty"`
	SecondaryEmail *string `json:"secondary_email,omitempty"`
	TertiaryEmail  *string `json:"tertiary_email,omitempty"`
}
