// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type InviteGroup struct {
	CreateBy map[string]interface{} `json:"create_by,omitempty"`
	Created  time.Time              `json:"created"`
	ID       int64                  `json:"id"`
	Invite   string                 `json:"invite"`
	UpdateBy map[string]interface{} `json:"update_by,omitempty"`
	Updated  time.Time              `json:"updated"`
}
