// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ManagementAgent struct {
	Contact              *int64    `json:"contact,omitempty"`
	Created              time.Time `json:"created"`
	DefaultInvoiceFilter *int64    `json:"default_invoice_filter,omitempty"`
	DefaultMeldFilter    *int64    `json:"default_meld_filter,omitempty"`
	FirstName            *string   `json:"first_name,omitempty"`
	ID                   int64     `json:"id"`
	IsActive             *bool     `json:"is_active,omitempty"`
	LastName             *string   `json:"last_name,omitempty"`
	Role                 int64     `json:"role"`
	Updated              time.Time `json:"updated"`
}
