// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldExpendituresListViewSerializerList struct {
	Amount                string                         `json:"amount"`
	Created               time.Time                      `json:"created"`
	ExpendituresLineItems []MeldExpendituresListLineItem `json:"expenditures_line_items"`
	ID                    int64                          `json:"id"`
	Meld                  MeldExpendituresListMeld       `json:"meld"`
	Notes                 *string                        `json:"notes,omitempty"`
	Status                *StatusD0bEnum                 `json:"status,omitempty"`
	Updated               time.Time                      `json:"updated"`
}
