// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldListViewUnitDisplayAddress struct {
	City           *string                `json:"city,omitempty"`
	Country        *string                `json:"country,omitempty"`
	CountyProvince *string                `json:"county_province,omitempty"`
	CreateBy       map[string]interface{} `json:"create_by,omitempty"`
	Created        time.Time              `json:"created"`
	ID             int64                  `json:"id"`
	IsActive       *bool                  `json:"is_active,omitempty"`
	Line1          *string                `json:"line_1,omitempty"`
	Line2          *string                `json:"line_2,omitempty"`
	Line3          *string                `json:"line_3,omitempty"`
	Postcode       string                 `json:"postcode"`
	PropertyName   *string                `json:"property_name,omitempty"`
	UpdateBy       map[string]interface{} `json:"update_by,omitempty"`
	Updated        time.Time              `json:"updated"`
}

type MeldListViewUnit struct {
	Apartment             *string                        `json:"apartment,omitempty"`
	ApprovalCurrencyLimit *string                        `json:"approval_currency_limit,omitempty"`
	Building              *int64                         `json:"building,omitempty"`
	CreateBy              map[string]interface{}         `json:"create_by,omitempty"`
	Created               time.Time                      `json:"created"`
	Department            *string                        `json:"department,omitempty"`
	DisplayAddress        MeldListViewUnitDisplayAddress `json:"display_address"`
	Floor                 *int64                         `json:"floor,omitempty"`
	ID                    int64                          `json:"id"`
	IsActive              *bool                          `json:"is_active,omitempty"`
	Prop                  *MeldListViewProperty          `json:"prop,omitempty"`
	Room                  *string                        `json:"room,omitempty"`
	Suite                 *string                        `json:"suite,omitempty"`
	SupplementalData      map[string]interface{}         `json:"supplemental_data,omitempty"`
	Unit                  *string                        `json:"unit,omitempty"`
	UnitAddress           *int64                         `json:"unit_address,omitempty"`
	UpdateBy              map[string]interface{}         `json:"update_by,omitempty"`
	Updated               time.Time                      `json:"updated"`
}
