// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MeldInvoiceListProperty struct {
	City           *string `json:"city,omitempty"`
	CountyProvince *string `json:"county_province,omitempty"`
	ID             int64   `json:"id"`
	Line1          *string `json:"line_1,omitempty"`
	Postcode       string  `json:"postcode"`
	PropertyName   *string `json:"property_name,omitempty"`
}
