// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldInvoiceSerializerDetail struct {
	Amount           *string                `json:"amount,omitempty"`
	AttachmentURL    string                 `json:"attachment_url"`
	CreateBy         map[string]interface{} `json:"create_by,omitempty"`
	Created          time.Time              `json:"created"`
	ID               int64                  `json:"id"`
	ManagementAgent  *int64                 `json:"management_agent,omitempty"`
	Meld             MeldInvoiceListMeld    `json:"meld"`
	Notes            *string                `json:"notes,omitempty"`
	Payment          BasePayment            `json:"payment"`
	PaymentRequested *time.Time             `json:"payment_requested,omitempty"`
	Status           *Status09fEnum         `json:"status,omitempty"`
	UpdateBy         map[string]interface{} `json:"update_by,omitempty"`
	Updated          time.Time              `json:"updated"`
	Vendor           MeldInvoiceListVendor  `json:"vendor"`
}
