// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MeldInvoiceListViewUnit struct {
	Apartment      *string                       `json:"apartment,omitempty"`
	Building       BaseBuilding                  `json:"building"`
	Department     *string                       `json:"department,omitempty"`
	DisplayAddress MeldInvoiceListDisplayAddress `json:"display_address"`
	Floor          BaseFloor                     `json:"floor"`
	ID             int64                         `json:"id"`
	Prop           MeldInvoiceListProperty       `json:"prop"`
	Room           *string                       `json:"room,omitempty"`
	Suite          *string                       `json:"suite,omitempty"`
	Unit           *string                       `json:"unit,omitempty"`
}
