// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldExpendituresListLineItem struct {
	Created      time.Time `json:"created"`
	Description  string    `json:"description"`
	Expenditures *int64    `json:"expenditures,omitempty"`
	ID           int64     `json:"id"`
	Quantity     string    `json:"quantity"`
	UnitCost     *string   `json:"unit_cost,omitempty"`
	UnitPrice    string    `json:"unit_price"`
	Updated      time.Time `json:"updated"`
}
