// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MeldListViewInHouseMeldServicer struct {
	Agent MeldListViewManagementAgent `json:"agent"`
	ID    int64                       `json:"id"`
}
