// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldListViewInviteAssignment struct {
	Accepted    *time.Time             `json:"accepted,omitempty"`
	Canceled    *time.Time             `json:"canceled,omitempty"`
	CreateBy    map[string]interface{} `json:"create_by,omitempty"`
	Created     time.Time              `json:"created"`
	ID          int64                  `json:"id"`
	InviteGroup InviteGroup            `json:"invite_group"`
	Meld        int64                  `json:"meld"`
	UpdateBy    map[string]interface{} `json:"update_by,omitempty"`
	Updated     time.Time              `json:"updated"`
}
