// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldExpendituresListProperty struct {
	City                *string   `json:"city,omitempty"`
	Country             *string   `json:"country,omitempty"`
	CountyProvince      *string   `json:"county_province,omitempty"`
	Created             time.Time `json:"created"`
	ID                  int64     `json:"id"`
	IsActive            *bool     `json:"is_active,omitempty"`
	Line1               *string   `json:"line_1,omitempty"`
	Line2               *string   `json:"line_2,omitempty"`
	Line3               *string   `json:"line_3,omitempty"`
	OtherAddressDetails *string   `json:"other_address_details,omitempty"`
	Postcode            string    `json:"postcode"`
	PropertyName        *string   `json:"property_name,omitempty"`
	Updated             time.Time `json:"updated"`
}
