// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldListViewManagementAgent struct {
	Created   time.Time `json:"created"`
	FirstName *string   `json:"first_name,omitempty"`
	ID        int64     `json:"id"`
	LastName  *string   `json:"last_name,omitempty"`
	Updated   time.Time `json:"updated"`
	User      BaseUser  `json:"user"`
}
