// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type MeldInvoiceListMeld struct {
	BriefDescription string                  `json:"brief_description"`
	Created          time.Time               `json:"created"`
	ID               int64                   `json:"id"`
	Prop             MeldInvoiceListProperty `json:"prop"`
	ReferenceID      *string                 `json:"reference_id,omitempty"`
	Unit             MeldInvoiceListViewUnit `json:"unit"`
}
