// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
	"time"
)

type MeldSerializerDetailManagementAgentCloser struct {
	AgentPreferences        int64                  `json:"agent_preferences"`
	Contact                 *int64                 `json:"contact,omitempty"`
	CreateBy                map[string]interface{} `json:"create_by,omitempty"`
	Created                 time.Time              `json:"created"`
	DefaultInvoiceFilter    *int64                 `json:"default_invoice_filter,omitempty"`
	DefaultMeldFilter       *int64                 `json:"default_meld_filter,omitempty"`
	FirstName               *string                `json:"first_name,omitempty"`
	ID                      int64                  `json:"id"`
	IsActive                *bool                  `json:"is_active,omitempty"`
	LastName                *string                `json:"last_name,omitempty"`
	Management              int64                  `json:"management"`
	NewNotificationSettings *int64                 `json:"new_notification_settings,omitempty"`
	PropertyGroups          []int64                `json:"property_groups"`
	Role                    int64                  `json:"role"`
	ShowTour                *bool                  `json:"show_tour,omitempty"`
	Title                   string                 `json:"title"`
	UpdateBy                map[string]interface{} `json:"update_by,omitempty"`
	Updated                 time.Time              `json:"updated"`
	User                    *int64                 `json:"user,omitempty"`
}

type MeldSerializerDetailManagementappointment struct {
	AvailabilitySegment MeldListviewManagementAvailabilitySegment `json:"availability_segment"`
	CreateBy            map[string]interface{}                    `json:"create_by,omitempty"`
	Created             time.Time                                 `json:"created"`
	ID                  int64                                     `json:"id"`
	Meld                int64                                     `json:"meld"`
	UpdateBy            map[string]interface{}                    `json:"update_by,omitempty"`
	Updated             time.Time                                 `json:"updated"`
}

type MeldSerializerDetailManagerCanceller struct {
	AgentPreferences        int64                  `json:"agent_preferences"`
	Contact                 *int64                 `json:"contact,omitempty"`
	CreateBy                map[string]interface{} `json:"create_by,omitempty"`
	Created                 time.Time              `json:"created"`
	DefaultInvoiceFilter    *int64                 `json:"default_invoice_filter,omitempty"`
	DefaultMeldFilter       *int64                 `json:"default_meld_filter,omitempty"`
	FirstName               *string                `json:"first_name,omitempty"`
	ID                      int64                  `json:"id"`
	IsActive                *bool                  `json:"is_active,omitempty"`
	LastName                *string                `json:"last_name,omitempty"`
	Management              int64                  `json:"management"`
	NewNotificationSettings *int64                 `json:"new_notification_settings,omitempty"`
	PropertyGroups          []int64                `json:"property_groups"`
	Role                    int64                  `json:"role"`
	ShowTour                *bool                  `json:"show_tour,omitempty"`
	Title                   string                 `json:"title"`
	UpdateBy                map[string]interface{} `json:"update_by,omitempty"`
	Updated                 time.Time              `json:"updated"`
	User                    *int64                 `json:"user,omitempty"`
}

type MeldSerializerDetailMeldExpenditures struct {
	Amount   *string                `json:"amount,omitempty"`
	CreateBy map[string]interface{} `json:"create_by,omitempty"`
	Created  time.Time              `json:"created"`
	ID       int64                  `json:"id"`
	Meld     int64                  `json:"meld"`
	Notes    *string                `json:"notes,omitempty"`
	Status   *StatusD0bEnum         `json:"status,omitempty"`
	UpdateBy map[string]interface{} `json:"update_by,omitempty"`
	Updated  time.Time              `json:"updated"`
}

type MeldSerializerDetailTenantRatingType string

const (
	MeldSerializerDetailTenantRatingTypeTenantRatingEnum MeldSerializerDetailTenantRatingType = "TenantRatingEnum"
	MeldSerializerDetailTenantRatingTypeNullEnum         MeldSerializerDetailTenantRatingType = "NullEnum"
)

type MeldSerializerDetailTenantRating struct {
	TenantRatingEnum *TenantRatingEnum
	NullEnum         *NullEnum

	Type MeldSerializerDetailTenantRatingType
}

func CreateMeldSerializerDetailTenantRatingTenantRatingEnum(tenantRatingEnum TenantRatingEnum) MeldSerializerDetailTenantRating {
	typ := MeldSerializerDetailTenantRatingTypeTenantRatingEnum

	return MeldSerializerDetailTenantRating{
		TenantRatingEnum: &tenantRatingEnum,
		Type:             typ,
	}
}

func CreateMeldSerializerDetailTenantRatingNullEnum(nullEnum NullEnum) MeldSerializerDetailTenantRating {
	typ := MeldSerializerDetailTenantRatingTypeNullEnum

	return MeldSerializerDetailTenantRating{
		NullEnum: &nullEnum,
		Type:     typ,
	}
}

func (u *MeldSerializerDetailTenantRating) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	tenantRatingEnum := new(TenantRatingEnum)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&tenantRatingEnum); err == nil {
		u.TenantRatingEnum = tenantRatingEnum
		u.Type = MeldSerializerDetailTenantRatingTypeTenantRatingEnum
		return nil
	}

	nullEnum := new(NullEnum)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&nullEnum); err == nil {
		u.NullEnum = nullEnum
		u.Type = MeldSerializerDetailTenantRatingTypeNullEnum
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u MeldSerializerDetailTenantRating) MarshalJSON() ([]byte, error) {
	if u.TenantRatingEnum != nil {
		return json.Marshal(u.TenantRatingEnum)
	}

	if u.NullEnum != nil {
		return json.Marshal(u.NullEnum)
	}

	return nil, nil
}

type MeldSerializerDetailVendorCloser struct {
	Address                int64                  `json:"address"`
	CreateBy               map[string]interface{} `json:"create_by,omitempty"`
	Created                time.Time              `json:"created"`
	Email                  *string                `json:"email,omitempty"`
	ExcludedPropertyGroups []int64                `json:"excluded_property_groups"`
	Fax                    *string                `json:"fax,omitempty"`
	ID                     int64                  `json:"id"`
	IsActive               *bool                  `json:"is_active,omitempty"`
	Managements            []int64                `json:"managements"`
	Name                   *string                `json:"name,omitempty"`
	Phone                  *string                `json:"phone,omitempty"`
	UpdateBy               map[string]interface{} `json:"update_by,omitempty"`
	Updated                time.Time              `json:"updated"`
}

type MeldSerializerDetailVendorappointment struct {
	AssignmentRequest   int64                     `json:"assignment_request"`
	AvailabilitySegment VendorAvailabilitySegment `json:"availability_segment"`
	CreateBy            map[string]interface{}    `json:"create_by,omitempty"`
	Created             time.Time                 `json:"created"`
	ID                  int64                     `json:"id"`
	Meld                int64                     `json:"meld"`
	UpdateBy            map[string]interface{}    `json:"update_by,omitempty"`
	Updated             time.Time                 `json:"updated"`
}

type MeldSerializerDetailOutput struct {
	Assigned                    *time.Time                                `json:"assigned,omitempty"`
	Assigner                    int64                                     `json:"assigner"`
	BriefDescription            string                                    `json:"brief_description"`
	CompletionDate              *time.Time                                `json:"completion_date,omitempty"`
	CompletionNotes             *string                                   `json:"completion_notes,omitempty"`
	CreateBy                    map[string]interface{}                    `json:"create_by,omitempty"`
	Created                     time.Time                                 `json:"created"`
	Creator                     int64                                     `json:"creator"`
	Description                 *string                                   `json:"description,omitempty"`
	DueDate                     *time.Time                                `json:"due_date,omitempty"`
	HasPets                     *bool                                     `json:"has_pets,omitempty"`
	HasRegisteredTenant         *bool                                     `json:"has_registered_tenant,omitempty"`
	ID                          int64                                     `json:"id"`
	InHouseServicers            []MeldListViewInHouseMeldServicer         `json:"in_house_servicers"`
	InviteAssignments           []MeldListViewInviteAssignment            `json:"invite_assignments"`
	IsActive                    *bool                                     `json:"is_active,omitempty"`
	MaintenanceNotes            *string                                   `json:"maintenance_notes,omitempty"`
	Management                  int64                                     `json:"management"`
	ManagementAgentCloser       MeldSerializerDetailManagementAgentCloser `json:"management_agent_closer"`
	Managementappointment       MeldSerializerDetailManagementappointment `json:"managementappointment"`
	ManagerCancellationReason   *string                                   `json:"manager_cancellation_reason,omitempty"`
	ManagerCancelled            *time.Time                                `json:"manager_cancelled,omitempty"`
	ManagerCanceller            MeldSerializerDetailManagerCanceller      `json:"manager_canceller"`
	MarkedComplete              *time.Time                                `json:"marked_complete,omitempty"`
	MeldExpenditures            MeldSerializerDetailMeldExpenditures      `json:"meld_expenditures"`
	MeldGroup                   string                                    `json:"meld_group"`
	NotifyOwner                 *bool                                     `json:"notify_owner,omitempty"`
	OpenWorkEntry               string                                    `json:"open_work_entry"`
	OwnerApprovalAcknowledged   *time.Time                                `json:"owner_approval_acknowledged,omitempty"`
	OwnerApprovalComment        *string                                   `json:"owner_approval_comment,omitempty"`
	OwnerApprovalCompletedDate  *time.Time                                `json:"owner_approval_completed_date,omitempty"`
	OwnerApprovalDollarAmount   *string                                   `json:"owner_approval_dollar_amount,omitempty"`
	OwnerApprovalRequestDate    *time.Time                                `json:"owner_approval_request_date,omitempty"`
	OwnerApprovalRequestMessage *string                                   `json:"owner_approval_request_message,omitempty"`
	OwnerApprovalStatus         *OwnerApprovalStatusEnum                  `json:"owner_approval_status,omitempty"`
	OwnerApprovedBy             *int64                                    `json:"owner_approved_by,omitempty"`
	OwnerNotifiedAssignment     *time.Time                                `json:"owner_notified_assignment,omitempty"`
	Parent                      *int64                                    `json:"parent,omitempty"`
	Pets                        *string                                   `json:"pets,omitempty"`
	Priority                    *PriorityEnum                             `json:"priority,omitempty"`
	Project                     *int64                                    `json:"project,omitempty"`
	Prop                        *MeldListViewProperty                     `json:"prop,omitempty"`
	ReasonCannotComplete        *string                                   `json:"reason_cannot_complete,omitempty"`
	RecurringMeld               *int64                                    `json:"recurring_meld,omitempty"`
	ReferenceID                 *string                                   `json:"reference_id,omitempty"`
	ReviewingTenant             *int64                                    `json:"reviewing_tenant,omitempty"`
	Started                     *time.Time                                `json:"started,omitempty"`
	Status                      *Status5c6Enum                            `json:"status,omitempty"`
	Tags                        []WriteableTag                            `json:"tags,omitempty"`
	TenantCanceller             *int64                                    `json:"tenant_canceller,omitempty"`
	TenantPresenceRequired      *bool                                     `json:"tenant_presence_required,omitempty"`
	TenantRating                *MeldSerializerDetailTenantRating         `json:"tenant_rating,omitempty"`
	TenantReview                *string                                   `json:"tenant_review,omitempty"`
	TenantReviewDate            *time.Time                                `json:"tenant_review_date,omitempty"`
	Tenants                     []Tenant                                  `json:"tenants,omitempty"`
	Unit                        *MeldListViewUnit                         `json:"unit,omitempty"`
	UpdateBy                    map[string]interface{}                    `json:"update_by,omitempty"`
	Updated                     time.Time                                 `json:"updated"`
	VendorAssignmentRequests    []VendorAssignmentRequest                 `json:"vendor_assignment_requests,omitempty"`
	VendorCloser                MeldSerializerDetailVendorCloser          `json:"vendor_closer"`
	Vendorappointment           MeldSerializerDetailVendorappointment     `json:"vendorappointment"`
	WorkCategory                WorkCategoryEnum                          `json:"work_category"`
	WorkLocation                string                                    `json:"work_location"`
}
