// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type MethodEnum string

const (
	MethodEnumCash  MethodEnum = "CASH"
	MethodEnumAch   MethodEnum = "ACH"
	MethodEnumCheck MethodEnum = "CHECK"
	MethodEnumCc    MethodEnum = "CC"
)

func (e MethodEnum) ToPointer() *MethodEnum {
	return &e
}

func (e *MethodEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CASH":
		fallthrough
	case "ACH":
		fallthrough
	case "CHECK":
		fallthrough
	case "CC":
		*e = MethodEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MethodEnum: %v", v)
	}
}
