// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NotificationSettingsInput struct {
	IncomingMeldFrequency   *IncomingMeldFrequencyEnum   `json:"incoming_meld_frequency,omitempty"`
	SmsNotifications        *bool                        `json:"sms_notifications,omitempty"`
	SuccessfulMeldFrequency *SuccessfulMeldFrequencyEnum `json:"successful_meld_frequency,omitempty"`
	Timezone                *TimezoneEnum                `json:"timezone,omitempty"`
}

type NotificationSettings struct {
	IncomingMeldFrequency   *IncomingMeldFrequencyEnum   `json:"incoming_meld_frequency,omitempty"`
	SmsNotifications        *bool                        `json:"sms_notifications,omitempty"`
	SuccessfulMeldFrequency *SuccessfulMeldFrequencyEnum `json:"successful_meld_frequency,omitempty"`
	Timezone                *TimezoneEnum                `json:"timezone,omitempty"`
	TimezoneHasBeenSet      bool                         `json:"timezone_has_been_set"`
}
