// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type NullEnum string

const (
	NullEnumLessThanNilGreaterThan NullEnum = "<nil>"
)

func (e NullEnum) ToPointer() *NullEnum {
	return &e
}

func (e *NullEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "<nil>":
		*e = NullEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NullEnum: %v", v)
	}
}
