// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type OwnerInput struct {
	Address        *Address            `json:"address,omitempty" form:"name=address,json" multipartForm:"name=address,json"`
	Contact        *Contact            `json:"contact,omitempty" form:"name=contact,json" multipartForm:"name=contact,json"`
	Email          string              `json:"email" form:"name=email" multipartForm:"name=email"`
	FirstName      string              `json:"first_name" form:"name=first_name" multipartForm:"name=first_name"`
	HubAccessLevel *HubAccessLevelEnum `json:"hub_access_level,omitempty" form:"name=hub_access_level" multipartForm:"name=hub_access_level"`
	InvitedToHub   *bool               `json:"invited_to_hub,omitempty" form:"name=invited_to_hub" multipartForm:"name=invited_to_hub"`
	LastName       string              `json:"last_name" form:"name=last_name" multipartForm:"name=last_name"`
	Properties     []int64             `json:"properties,omitempty" form:"name=properties" multipartForm:"name=properties"`
}

type Owner struct {
	Address        *Address            `json:"address,omitempty"`
	Contact        *Contact            `json:"contact,omitempty"`
	Created        time.Time           `json:"created"`
	Email          string              `json:"email"`
	FirstName      string              `json:"first_name"`
	HubAccessLevel *HubAccessLevelEnum `json:"hub_access_level,omitempty"`
	ID             int64               `json:"id"`
	InvitedToHub   *bool               `json:"invited_to_hub,omitempty"`
	IsActive       bool                `json:"is_active"`
	LastName       string              `json:"last_name"`
	Properties     []int64             `json:"properties,omitempty"`
	Updated        time.Time           `json:"updated"`
}
