// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaginatedPropertyGroupSerializerListList struct {
	Count    *int64                        `json:"count,omitempty"`
	Next     *string                       `json:"next,omitempty"`
	Previous *string                       `json:"previous,omitempty"`
	Results  []PropertyGroupSerializerList `json:"results,omitempty"`
}
