// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PatchedPropertyInput struct {
	City                *string `json:"city,omitempty" form:"name=city" multipartForm:"name=city"`
	Country             *string `json:"country,omitempty" form:"name=country" multipartForm:"name=country"`
	CountyProvince      *string `json:"county_province,omitempty" form:"name=county_province" multipartForm:"name=county_province"`
	Line1               *string `json:"line_1,omitempty" form:"name=line_1" multipartForm:"name=line_1"`
	Line2               *string `json:"line_2,omitempty" form:"name=line_2" multipartForm:"name=line_2"`
	Line3               *string `json:"line_3,omitempty" form:"name=line_3" multipartForm:"name=line_3"`
	MaintenanceNotes    *string `json:"maintenance_notes,omitempty" form:"name=maintenance_notes" multipartForm:"name=maintenance_notes"`
	OtherAddressDetails *string `json:"other_address_details,omitempty" form:"name=other_address_details" multipartForm:"name=other_address_details"`
	Owners              []int64 `json:"owners,omitempty" form:"name=owners" multipartForm:"name=owners"`
	Postcode            *string `json:"postcode,omitempty" form:"name=postcode" multipartForm:"name=postcode"`
	PropertyGroups      []int64 `json:"property_groups,omitempty" form:"name=property_groups" multipartForm:"name=property_groups"`
	PropertyName        *string `json:"property_name,omitempty" form:"name=property_name" multipartForm:"name=property_name"`
	Units               []int64 `json:"units,omitempty" form:"name=units" multipartForm:"name=units"`
}
