// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ProjectTypeEnum string

const (
	ProjectTypeEnumOther      ProjectTypeEnum = "OTHER"
	ProjectTypeEnumRenovation ProjectTypeEnum = "RENOVATION"
	ProjectTypeEnumTurn       ProjectTypeEnum = "TURN"
	ProjectTypeEnumMitigation ProjectTypeEnum = "MITIGATION"
)

func (e ProjectTypeEnum) ToPointer() *ProjectTypeEnum {
	return &e
}

func (e *ProjectTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OTHER":
		fallthrough
	case "RENOVATION":
		fallthrough
	case "TURN":
		fallthrough
	case "MITIGATION":
		*e = ProjectTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProjectTypeEnum: %v", v)
	}
}
