// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ProjectListViewSerializerUnit struct {
	Apartment        *string                           `json:"apartment,omitempty"`
	Created          time.Time                         `json:"created"`
	Department       *string                           `json:"department,omitempty"`
	ID               int64                             `json:"id"`
	IsActive         *bool                             `json:"is_active,omitempty"`
	MaintenanceNotes *string                           `json:"maintenance_notes,omitempty"`
	Prop             ProjectListViewSerializerProperty `json:"prop"`
	Room             *string                           `json:"room,omitempty"`
	Suite            *string                           `json:"suite,omitempty"`
	Unit             *string                           `json:"unit,omitempty"`
	Updated          time.Time                         `json:"updated"`
}
