// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ProjectListViewSerializerProperty struct {
	City           *string   `json:"city,omitempty"`
	CountyProvince *string   `json:"county_province,omitempty"`
	Created        time.Time `json:"created"`
	ID             int64     `json:"id"`
	IsActive       *bool     `json:"is_active,omitempty"`
	Line1          *string   `json:"line_1,omitempty"`
	Line2          *string   `json:"line_2,omitempty"`
	Line3          *string   `json:"line_3,omitempty"`
	Postcode       string    `json:"postcode"`
	Updated        time.Time `json:"updated"`
}
