// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type PropertyInput struct {
	City                string  `json:"city" form:"name=city" multipartForm:"name=city"`
	Country             *string `json:"country,omitempty" form:"name=country" multipartForm:"name=country"`
	CountyProvince      string  `json:"county_province" form:"name=county_province" multipartForm:"name=county_province"`
	Line1               string  `json:"line_1" form:"name=line_1" multipartForm:"name=line_1"`
	Line2               *string `json:"line_2,omitempty" form:"name=line_2" multipartForm:"name=line_2"`
	Line3               *string `json:"line_3,omitempty" form:"name=line_3" multipartForm:"name=line_3"`
	MaintenanceNotes    *string `json:"maintenance_notes,omitempty" form:"name=maintenance_notes" multipartForm:"name=maintenance_notes"`
	OtherAddressDetails *string `json:"other_address_details,omitempty" form:"name=other_address_details" multipartForm:"name=other_address_details"`
	Owners              []int64 `json:"owners,omitempty" form:"name=owners" multipartForm:"name=owners"`
	Postcode            string  `json:"postcode" form:"name=postcode" multipartForm:"name=postcode"`
	PropertyGroups      []int64 `json:"property_groups,omitempty" form:"name=property_groups" multipartForm:"name=property_groups"`
	PropertyName        *string `json:"property_name,omitempty" form:"name=property_name" multipartForm:"name=property_name"`
	Units               []int64 `json:"units,omitempty" form:"name=units" multipartForm:"name=units"`
}

type Property struct {
	City                string    `json:"city"`
	Country             *string   `json:"country,omitempty"`
	CountyProvince      string    `json:"county_province"`
	Created             time.Time `json:"created"`
	ID                  int64     `json:"id"`
	IsActive            bool      `json:"is_active"`
	Line1               string    `json:"line_1"`
	Line2               *string   `json:"line_2,omitempty"`
	Line3               *string   `json:"line_3,omitempty"`
	MaintenanceNotes    *string   `json:"maintenance_notes,omitempty"`
	OtherAddressDetails *string   `json:"other_address_details,omitempty"`
	Owners              []int64   `json:"owners,omitempty"`
	Postcode            string    `json:"postcode"`
	PropertyGroups      []int64   `json:"property_groups,omitempty"`
	PropertyName        *string   `json:"property_name,omitempty"`
	Units               []int64   `json:"units,omitempty"`
	Updated             time.Time `json:"updated"`
}
