// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type PropertyGroupSerializerList struct {
	Created time.Time `json:"created"`
	ID      int64     `json:"id"`
	Name    string    `json:"name"`
	Updated time.Time `json:"updated"`
}
