// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ResidentInput1 struct {
	Address   interface{} `form:"name=address,json" multipartForm:"name=address,json"`
	Contact   *Contact    `form:"name=contact,json" multipartForm:"name=contact,json"`
	FirstName string      `form:"name=first_name" multipartForm:"name=first_name"`
	// Send an invite to the resident to access PropertyMeld
	Invite               *bool                      `form:"name=invite" multipartForm:"name=invite"`
	LastName             string                     `form:"name=last_name" multipartForm:"name=last_name"`
	MiddleName           *string                    `form:"name=middle_name" multipartForm:"name=middle_name"`
	Notes                *string                    `form:"name=notes" multipartForm:"name=notes"`
	NotificationSettings *NotificationSettingsInput `form:"name=notification_settings,json" multipartForm:"name=notification_settings,json"`
	Units                []int64                    `form:"name=units" multipartForm:"name=units"`
}

type ResidentAddress struct {
	City           string  `json:"city"`
	Country        *string `json:"country,omitempty"`
	CountyProvince string  `json:"county_province"`
	Line1          string  `json:"line_1"`
	Line2          *string `json:"line_2,omitempty"`
	Line3          *string `json:"line_3,omitempty"`
	Postcode       string  `json:"postcode"`
}

type Resident struct {
	Address   *ResidentAddress `json:"address,omitempty"`
	Contact   *Contact         `json:"contact,omitempty"`
	Created   time.Time        `json:"created"`
	FirstName string           `json:"first_name"`
	ID        int64            `json:"id"`
	// Send an invite to the resident to access PropertyMeld
	Invite               *bool                 `json:"invite,omitempty"`
	IsActive             bool                  `json:"is_active"`
	LastName             string                `json:"last_name"`
	MiddleName           *string               `json:"middle_name,omitempty"`
	Notes                *string               `json:"notes,omitempty"`
	NotificationSettings *NotificationSettings `json:"notification_settings,omitempty"`
	Units                []int64               `json:"units,omitempty"`
	Updated              time.Time             `json:"updated"`
}

type ResidentInput struct {
	Address   *ResidentAddress `json:"address,omitempty"`
	Contact   *Contact         `json:"contact,omitempty"`
	FirstName string           `json:"first_name"`
	// Send an invite to the resident to access PropertyMeld
	Invite               *bool                      `json:"invite,omitempty"`
	LastName             string                     `json:"last_name"`
	MiddleName           *string                    `json:"middle_name,omitempty"`
	Notes                *string                    `json:"notes,omitempty"`
	NotificationSettings *NotificationSettingsInput `json:"notification_settings,omitempty"`
	Units                []int64                    `json:"units,omitempty"`
}
