// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Status09fEnum string

const (
	Status09fEnumDraft     Status09fEnum = "DRAFT"
	Status09fEnumSubmitted Status09fEnum = "SUBMITTED"
	Status09fEnumInReview  Status09fEnum = "IN_REVIEW"
	Status09fEnumHold      Status09fEnum = "HOLD"
	Status09fEnumDeclined  Status09fEnum = "DECLINED"
	Status09fEnumApproved  Status09fEnum = "APPROVED"
	Status09fEnumPaid      Status09fEnum = "PAID"
)

func (e Status09fEnum) ToPointer() *Status09fEnum {
	return &e
}

func (e *Status09fEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DRAFT":
		fallthrough
	case "SUBMITTED":
		fallthrough
	case "IN_REVIEW":
		fallthrough
	case "HOLD":
		fallthrough
	case "DECLINED":
		fallthrough
	case "APPROVED":
		fallthrough
	case "PAID":
		*e = Status09fEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status09fEnum: %v", v)
	}
}
