// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Status5c6Enum string

const (
	Status5c6EnumOpen                              Status5c6Enum = "OPEN"
	Status5c6EnumManagerCanceled                   Status5c6Enum = "MANAGER_CANCELED"
	Status5c6EnumTenantCanceled                    Status5c6Enum = "TENANT_CANCELED"
	Status5c6EnumPendingEstimates                  Status5c6Enum = "PENDING_ESTIMATES"
	Status5c6EnumPendingTenantAvailability         Status5c6Enum = "PENDING_TENANT_AVAILABILITY"
	Status5c6EnumPendingMoreVendorAvailability     Status5c6Enum = "PENDING_MORE_VENDOR_AVAILABILITY"
	Status5c6EnumPendingMoreManagementAvailability Status5c6Enum = "PENDING_MORE_MANAGEMENT_AVAILABILITY"
	Status5c6EnumPendingCompletion                 Status5c6Enum = "PENDING_COMPLETION"
	Status5c6EnumCompleted                         Status5c6Enum = "COMPLETED"
	Status5c6EnumVendorCouldNotComplete            Status5c6Enum = "VENDOR_COULD_NOT_COMPLETE"
	Status5c6EnumMaintenanceCouldNotComplete       Status5c6Enum = "MAINTENANCE_COULD_NOT_COMPLETE"
	Status5c6EnumPendingVendor                     Status5c6Enum = "PENDING_VENDOR"
	Status5c6EnumPendingAssignment                 Status5c6Enum = "PENDING_ASSIGNMENT"
)

func (e Status5c6Enum) ToPointer() *Status5c6Enum {
	return &e
}

func (e *Status5c6Enum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OPEN":
		fallthrough
	case "MANAGER_CANCELED":
		fallthrough
	case "TENANT_CANCELED":
		fallthrough
	case "PENDING_ESTIMATES":
		fallthrough
	case "PENDING_TENANT_AVAILABILITY":
		fallthrough
	case "PENDING_MORE_VENDOR_AVAILABILITY":
		fallthrough
	case "PENDING_MORE_MANAGEMENT_AVAILABILITY":
		fallthrough
	case "PENDING_COMPLETION":
		fallthrough
	case "COMPLETED":
		fallthrough
	case "VENDOR_COULD_NOT_COMPLETE":
		fallthrough
	case "MAINTENANCE_COULD_NOT_COMPLETE":
		fallthrough
	case "PENDING_VENDOR":
		fallthrough
	case "PENDING_ASSIGNMENT":
		*e = Status5c6Enum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status5c6Enum: %v", v)
	}
}
