// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TenantRatingEnum int64

const (
	TenantRatingEnumOne   TenantRatingEnum = 1
	TenantRatingEnumTwo   TenantRatingEnum = 2
	TenantRatingEnumThree TenantRatingEnum = 3
	TenantRatingEnumFour  TenantRatingEnum = 4
	TenantRatingEnumFive  TenantRatingEnum = 5
)

func (e TenantRatingEnum) ToPointer() *TenantRatingEnum {
	return &e
}

func (e *TenantRatingEnum) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 1:
		fallthrough
	case 2:
		fallthrough
	case 3:
		fallthrough
	case 4:
		fallthrough
	case 5:
		*e = TenantRatingEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TenantRatingEnum: %v", v)
	}
}
