// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Tenant struct {
	FirstName  *string `json:"first_name,omitempty"`
	ID         int64   `json:"id"`
	LastName   *string `json:"last_name,omitempty"`
	MiddleName *string `json:"middle_name,omitempty"`
}
