// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TimezoneEnum string

const (
	TimezoneEnumAfricaAbidjan                  TimezoneEnum = "Africa/Abidjan"
	TimezoneEnumAfricaAccra                    TimezoneEnum = "Africa/Accra"
	TimezoneEnumAfricaAddisAbaba               TimezoneEnum = "Africa/Addis_Ababa"
	TimezoneEnumAfricaAlgiers                  TimezoneEnum = "Africa/Algiers"
	TimezoneEnumAfricaAsmara                   TimezoneEnum = "Africa/Asmara"
	TimezoneEnumAfricaAsmera                   TimezoneEnum = "Africa/Asmera"
	TimezoneEnumAfricaBamako                   TimezoneEnum = "Africa/Bamako"
	TimezoneEnumAfricaBangui                   TimezoneEnum = "Africa/Bangui"
	TimezoneEnumAfricaBanjul                   TimezoneEnum = "Africa/Banjul"
	TimezoneEnumAfricaBissau                   TimezoneEnum = "Africa/Bissau"
	TimezoneEnumAfricaBlantyre                 TimezoneEnum = "Africa/Blantyre"
	TimezoneEnumAfricaBrazzaville              TimezoneEnum = "Africa/Brazzaville"
	TimezoneEnumAfricaBujumbura                TimezoneEnum = "Africa/Bujumbura"
	TimezoneEnumAfricaCairo                    TimezoneEnum = "Africa/Cairo"
	TimezoneEnumAfricaCasablanca               TimezoneEnum = "Africa/Casablanca"
	TimezoneEnumAfricaCeuta                    TimezoneEnum = "Africa/Ceuta"
	TimezoneEnumAfricaConakry                  TimezoneEnum = "Africa/Conakry"
	TimezoneEnumAfricaDakar                    TimezoneEnum = "Africa/Dakar"
	TimezoneEnumAfricaDarEsSalaam              TimezoneEnum = "Africa/Dar_es_Salaam"
	TimezoneEnumAfricaDjibouti                 TimezoneEnum = "Africa/Djibouti"
	TimezoneEnumAfricaDouala                   TimezoneEnum = "Africa/Douala"
	TimezoneEnumAfricaElAaiun                  TimezoneEnum = "Africa/El_Aaiun"
	TimezoneEnumAfricaFreetown                 TimezoneEnum = "Africa/Freetown"
	TimezoneEnumAfricaGaborone                 TimezoneEnum = "Africa/Gaborone"
	TimezoneEnumAfricaHarare                   TimezoneEnum = "Africa/Harare"
	TimezoneEnumAfricaJohannesburg             TimezoneEnum = "Africa/Johannesburg"
	TimezoneEnumAfricaJuba                     TimezoneEnum = "Africa/Juba"
	TimezoneEnumAfricaKampala                  TimezoneEnum = "Africa/Kampala"
	TimezoneEnumAfricaKhartoum                 TimezoneEnum = "Africa/Khartoum"
	TimezoneEnumAfricaKigali                   TimezoneEnum = "Africa/Kigali"
	TimezoneEnumAfricaKinshasa                 TimezoneEnum = "Africa/Kinshasa"
	TimezoneEnumAfricaLagos                    TimezoneEnum = "Africa/Lagos"
	TimezoneEnumAfricaLibreville               TimezoneEnum = "Africa/Libreville"
	TimezoneEnumAfricaLome                     TimezoneEnum = "Africa/Lome"
	TimezoneEnumAfricaLuanda                   TimezoneEnum = "Africa/Luanda"
	TimezoneEnumAfricaLubumbashi               TimezoneEnum = "Africa/Lubumbashi"
	TimezoneEnumAfricaLusaka                   TimezoneEnum = "Africa/Lusaka"
	TimezoneEnumAfricaMalabo                   TimezoneEnum = "Africa/Malabo"
	TimezoneEnumAfricaMaputo                   TimezoneEnum = "Africa/Maputo"
	TimezoneEnumAfricaMaseru                   TimezoneEnum = "Africa/Maseru"
	TimezoneEnumAfricaMbabane                  TimezoneEnum = "Africa/Mbabane"
	TimezoneEnumAfricaMogadishu                TimezoneEnum = "Africa/Mogadishu"
	TimezoneEnumAfricaMonrovia                 TimezoneEnum = "Africa/Monrovia"
	TimezoneEnumAfricaNairobi                  TimezoneEnum = "Africa/Nairobi"
	TimezoneEnumAfricaNdjamena                 TimezoneEnum = "Africa/Ndjamena"
	TimezoneEnumAfricaNiamey                   TimezoneEnum = "Africa/Niamey"
	TimezoneEnumAfricaNouakchott               TimezoneEnum = "Africa/Nouakchott"
	TimezoneEnumAfricaOuagadougou              TimezoneEnum = "Africa/Ouagadougou"
	TimezoneEnumAfricaPortoNovo                TimezoneEnum = "Africa/Porto-Novo"
	TimezoneEnumAfricaSaoTome                  TimezoneEnum = "Africa/Sao_Tome"
	TimezoneEnumAfricaTimbuktu                 TimezoneEnum = "Africa/Timbuktu"
	TimezoneEnumAfricaTripoli                  TimezoneEnum = "Africa/Tripoli"
	TimezoneEnumAfricaTunis                    TimezoneEnum = "Africa/Tunis"
	TimezoneEnumAfricaWindhoek                 TimezoneEnum = "Africa/Windhoek"
	TimezoneEnumAmericaAdak                    TimezoneEnum = "America/Adak"
	TimezoneEnumAmericaAnchorage               TimezoneEnum = "America/Anchorage"
	TimezoneEnumAmericaAnguilla                TimezoneEnum = "America/Anguilla"
	TimezoneEnumAmericaAntigua                 TimezoneEnum = "America/Antigua"
	TimezoneEnumAmericaAraguaina               TimezoneEnum = "America/Araguaina"
	TimezoneEnumAmericaArgentinaBuenosAires    TimezoneEnum = "America/Argentina/Buenos_Aires"
	TimezoneEnumAmericaArgentinaCatamarca      TimezoneEnum = "America/Argentina/Catamarca"
	TimezoneEnumAmericaArgentinaComodRivadavia TimezoneEnum = "America/Argentina/ComodRivadavia"
	TimezoneEnumAmericaArgentinaCordoba        TimezoneEnum = "America/Argentina/Cordoba"
	TimezoneEnumAmericaArgentinaJujuy          TimezoneEnum = "America/Argentina/Jujuy"
	TimezoneEnumAmericaArgentinaLaRioja        TimezoneEnum = "America/Argentina/La_Rioja"
	TimezoneEnumAmericaArgentinaMendoza        TimezoneEnum = "America/Argentina/Mendoza"
	TimezoneEnumAmericaArgentinaRioGallegos    TimezoneEnum = "America/Argentina/Rio_Gallegos"
	TimezoneEnumAmericaArgentinaSalta          TimezoneEnum = "America/Argentina/Salta"
	TimezoneEnumAmericaArgentinaSanJuan        TimezoneEnum = "America/Argentina/San_Juan"
	TimezoneEnumAmericaArgentinaSanLuis        TimezoneEnum = "America/Argentina/San_Luis"
	TimezoneEnumAmericaArgentinaTucuman        TimezoneEnum = "America/Argentina/Tucuman"
	TimezoneEnumAmericaArgentinaUshuaia        TimezoneEnum = "America/Argentina/Ushuaia"
	TimezoneEnumAmericaAruba                   TimezoneEnum = "America/Aruba"
	TimezoneEnumAmericaAsuncion                TimezoneEnum = "America/Asuncion"
	TimezoneEnumAmericaAtikokan                TimezoneEnum = "America/Atikokan"
	TimezoneEnumAmericaAtka                    TimezoneEnum = "America/Atka"
	TimezoneEnumAmericaBahia                   TimezoneEnum = "America/Bahia"
	TimezoneEnumAmericaBahiaBanderas           TimezoneEnum = "America/Bahia_Banderas"
	TimezoneEnumAmericaBarbados                TimezoneEnum = "America/Barbados"
	TimezoneEnumAmericaBelem                   TimezoneEnum = "America/Belem"
	TimezoneEnumAmericaBelize                  TimezoneEnum = "America/Belize"
	TimezoneEnumAmericaBlancSablon             TimezoneEnum = "America/Blanc-Sablon"
	TimezoneEnumAmericaBoaVista                TimezoneEnum = "America/Boa_Vista"
	TimezoneEnumAmericaBogota                  TimezoneEnum = "America/Bogota"
	TimezoneEnumAmericaBoise                   TimezoneEnum = "America/Boise"
	TimezoneEnumAmericaBuenosAires             TimezoneEnum = "America/Buenos_Aires"
	TimezoneEnumAmericaCambridgeBay            TimezoneEnum = "America/Cambridge_Bay"
	TimezoneEnumAmericaCampoGrande             TimezoneEnum = "America/Campo_Grande"
	TimezoneEnumAmericaCancun                  TimezoneEnum = "America/Cancun"
	TimezoneEnumAmericaCaracas                 TimezoneEnum = "America/Caracas"
	TimezoneEnumAmericaCatamarca               TimezoneEnum = "America/Catamarca"
	TimezoneEnumAmericaCayenne                 TimezoneEnum = "America/Cayenne"
	TimezoneEnumAmericaCayman                  TimezoneEnum = "America/Cayman"
	TimezoneEnumAmericaChicago                 TimezoneEnum = "America/Chicago"
	TimezoneEnumAmericaChihuahua               TimezoneEnum = "America/Chihuahua"
	TimezoneEnumAmericaCoralHarbour            TimezoneEnum = "America/Coral_Harbour"
	TimezoneEnumAmericaCordoba                 TimezoneEnum = "America/Cordoba"
	TimezoneEnumAmericaCostaRica               TimezoneEnum = "America/Costa_Rica"
	TimezoneEnumAmericaCreston                 TimezoneEnum = "America/Creston"
	TimezoneEnumAmericaCuiaba                  TimezoneEnum = "America/Cuiaba"
	TimezoneEnumAmericaCuracao                 TimezoneEnum = "America/Curacao"
	TimezoneEnumAmericaDanmarkshavn            TimezoneEnum = "America/Danmarkshavn"
	TimezoneEnumAmericaDawson                  TimezoneEnum = "America/Dawson"
	TimezoneEnumAmericaDawsonCreek             TimezoneEnum = "America/Dawson_Creek"
	TimezoneEnumAmericaDenver                  TimezoneEnum = "America/Denver"
	TimezoneEnumAmericaDetroit                 TimezoneEnum = "America/Detroit"
	TimezoneEnumAmericaDominica                TimezoneEnum = "America/Dominica"
	TimezoneEnumAmericaEdmonton                TimezoneEnum = "America/Edmonton"
	TimezoneEnumAmericaEirunepe                TimezoneEnum = "America/Eirunepe"
	TimezoneEnumAmericaElSalvador              TimezoneEnum = "America/El_Salvador"
	TimezoneEnumAmericaEnsenada                TimezoneEnum = "America/Ensenada"
	TimezoneEnumAmericaFortNelson              TimezoneEnum = "America/Fort_Nelson"
	TimezoneEnumAmericaFortWayne               TimezoneEnum = "America/Fort_Wayne"
	TimezoneEnumAmericaFortaleza               TimezoneEnum = "America/Fortaleza"
	TimezoneEnumAmericaGlaceBay                TimezoneEnum = "America/Glace_Bay"
	TimezoneEnumAmericaGodthab                 TimezoneEnum = "America/Godthab"
	TimezoneEnumAmericaGooseBay                TimezoneEnum = "America/Goose_Bay"
	TimezoneEnumAmericaGrandTurk               TimezoneEnum = "America/Grand_Turk"
	TimezoneEnumAmericaGrenada                 TimezoneEnum = "America/Grenada"
	TimezoneEnumAmericaGuadeloupe              TimezoneEnum = "America/Guadeloupe"
	TimezoneEnumAmericaGuatemala               TimezoneEnum = "America/Guatemala"
	TimezoneEnumAmericaGuayaquil               TimezoneEnum = "America/Guayaquil"
	TimezoneEnumAmericaGuyana                  TimezoneEnum = "America/Guyana"
	TimezoneEnumAmericaHalifax                 TimezoneEnum = "America/Halifax"
	TimezoneEnumAmericaHavana                  TimezoneEnum = "America/Havana"
	TimezoneEnumAmericaHermosillo              TimezoneEnum = "America/Hermosillo"
	TimezoneEnumAmericaIndianaIndianapolis     TimezoneEnum = "America/Indiana/Indianapolis"
	TimezoneEnumAmericaIndianaKnox             TimezoneEnum = "America/Indiana/Knox"
	TimezoneEnumAmericaIndianaMarengo          TimezoneEnum = "America/Indiana/Marengo"
	TimezoneEnumAmericaIndianaPetersburg       TimezoneEnum = "America/Indiana/Petersburg"
	TimezoneEnumAmericaIndianaTellCity         TimezoneEnum = "America/Indiana/Tell_City"
	TimezoneEnumAmericaIndianaVevay            TimezoneEnum = "America/Indiana/Vevay"
	TimezoneEnumAmericaIndianaVincennes        TimezoneEnum = "America/Indiana/Vincennes"
	TimezoneEnumAmericaIndianaWinamac          TimezoneEnum = "America/Indiana/Winamac"
	TimezoneEnumAmericaIndianapolis            TimezoneEnum = "America/Indianapolis"
	TimezoneEnumAmericaInuvik                  TimezoneEnum = "America/Inuvik"
	TimezoneEnumAmericaIqaluit                 TimezoneEnum = "America/Iqaluit"
	TimezoneEnumAmericaJamaica                 TimezoneEnum = "America/Jamaica"
	TimezoneEnumAmericaJujuy                   TimezoneEnum = "America/Jujuy"
	TimezoneEnumAmericaJuneau                  TimezoneEnum = "America/Juneau"
	TimezoneEnumAmericaKentuckyLouisville      TimezoneEnum = "America/Kentucky/Louisville"
	TimezoneEnumAmericaKentuckyMonticello      TimezoneEnum = "America/Kentucky/Monticello"
	TimezoneEnumAmericaKnoxIn                  TimezoneEnum = "America/Knox_IN"
	TimezoneEnumAmericaKralendijk              TimezoneEnum = "America/Kralendijk"
	TimezoneEnumAmericaLaPaz                   TimezoneEnum = "America/La_Paz"
	TimezoneEnumAmericaLima                    TimezoneEnum = "America/Lima"
	TimezoneEnumAmericaLosAngeles              TimezoneEnum = "America/Los_Angeles"
	TimezoneEnumAmericaLouisville              TimezoneEnum = "America/Louisville"
	TimezoneEnumAmericaLowerPrinces            TimezoneEnum = "America/Lower_Princes"
	TimezoneEnumAmericaMaceio                  TimezoneEnum = "America/Maceio"
	TimezoneEnumAmericaManagua                 TimezoneEnum = "America/Managua"
	TimezoneEnumAmericaManaus                  TimezoneEnum = "America/Manaus"
	TimezoneEnumAmericaMarigot                 TimezoneEnum = "America/Marigot"
	TimezoneEnumAmericaMartinique              TimezoneEnum = "America/Martinique"
	TimezoneEnumAmericaMatamoros               TimezoneEnum = "America/Matamoros"
	TimezoneEnumAmericaMazatlan                TimezoneEnum = "America/Mazatlan"
	TimezoneEnumAmericaMendoza                 TimezoneEnum = "America/Mendoza"
	TimezoneEnumAmericaMenominee               TimezoneEnum = "America/Menominee"
	TimezoneEnumAmericaMerida                  TimezoneEnum = "America/Merida"
	TimezoneEnumAmericaMetlakatla              TimezoneEnum = "America/Metlakatla"
	TimezoneEnumAmericaMexicoCity              TimezoneEnum = "America/Mexico_City"
	TimezoneEnumAmericaMiquelon                TimezoneEnum = "America/Miquelon"
	TimezoneEnumAmericaMoncton                 TimezoneEnum = "America/Moncton"
	TimezoneEnumAmericaMonterrey               TimezoneEnum = "America/Monterrey"
	TimezoneEnumAmericaMontevideo              TimezoneEnum = "America/Montevideo"
	TimezoneEnumAmericaMontreal                TimezoneEnum = "America/Montreal"
	TimezoneEnumAmericaMontserrat              TimezoneEnum = "America/Montserrat"
	TimezoneEnumAmericaNassau                  TimezoneEnum = "America/Nassau"
	TimezoneEnumAmericaNewYork                 TimezoneEnum = "America/New_York"
	TimezoneEnumAmericaNipigon                 TimezoneEnum = "America/Nipigon"
	TimezoneEnumAmericaNome                    TimezoneEnum = "America/Nome"
	TimezoneEnumAmericaNoronha                 TimezoneEnum = "America/Noronha"
	TimezoneEnumAmericaNorthDakotaBeulah       TimezoneEnum = "America/North_Dakota/Beulah"
	TimezoneEnumAmericaNorthDakotaCenter       TimezoneEnum = "America/North_Dakota/Center"
	TimezoneEnumAmericaNorthDakotaNewSalem     TimezoneEnum = "America/North_Dakota/New_Salem"
	TimezoneEnumAmericaNuuk                    TimezoneEnum = "America/Nuuk"
	TimezoneEnumAmericaOjinaga                 TimezoneEnum = "America/Ojinaga"
	TimezoneEnumAmericaPanama                  TimezoneEnum = "America/Panama"
	TimezoneEnumAmericaPangnirtung             TimezoneEnum = "America/Pangnirtung"
	TimezoneEnumAmericaParamaribo              TimezoneEnum = "America/Paramaribo"
	TimezoneEnumAmericaPhoenix                 TimezoneEnum = "America/Phoenix"
	TimezoneEnumAmericaPortAuPrince            TimezoneEnum = "America/Port-au-Prince"
	TimezoneEnumAmericaPortOfSpain             TimezoneEnum = "America/Port_of_Spain"
	TimezoneEnumAmericaPortoAcre               TimezoneEnum = "America/Porto_Acre"
	TimezoneEnumAmericaPortoVelho              TimezoneEnum = "America/Porto_Velho"
	TimezoneEnumAmericaPuertoRico              TimezoneEnum = "America/Puerto_Rico"
	TimezoneEnumAmericaPuntaArenas             TimezoneEnum = "America/Punta_Arenas"
	TimezoneEnumAmericaRainyRiver              TimezoneEnum = "America/Rainy_River"
	TimezoneEnumAmericaRankinInlet             TimezoneEnum = "America/Rankin_Inlet"
	TimezoneEnumAmericaRecife                  TimezoneEnum = "America/Recife"
	TimezoneEnumAmericaRegina                  TimezoneEnum = "America/Regina"
	TimezoneEnumAmericaResolute                TimezoneEnum = "America/Resolute"
	TimezoneEnumAmericaRioBranco               TimezoneEnum = "America/Rio_Branco"
	TimezoneEnumAmericaRosario                 TimezoneEnum = "America/Rosario"
	TimezoneEnumAmericaSantaIsabel             TimezoneEnum = "America/Santa_Isabel"
	TimezoneEnumAmericaSantarem                TimezoneEnum = "America/Santarem"
	TimezoneEnumAmericaSantiago                TimezoneEnum = "America/Santiago"
	TimezoneEnumAmericaSantoDomingo            TimezoneEnum = "America/Santo_Domingo"
	TimezoneEnumAmericaSaoPaulo                TimezoneEnum = "America/Sao_Paulo"
	TimezoneEnumAmericaScoresbysund            TimezoneEnum = "America/Scoresbysund"
	TimezoneEnumAmericaShiprock                TimezoneEnum = "America/Shiprock"
	TimezoneEnumAmericaSitka                   TimezoneEnum = "America/Sitka"
	TimezoneEnumAmericaStBarthelemy            TimezoneEnum = "America/St_Barthelemy"
	TimezoneEnumAmericaStJohns                 TimezoneEnum = "America/St_Johns"
	TimezoneEnumAmericaStKitts                 TimezoneEnum = "America/St_Kitts"
	TimezoneEnumAmericaStLucia                 TimezoneEnum = "America/St_Lucia"
	TimezoneEnumAmericaStThomas                TimezoneEnum = "America/St_Thomas"
	TimezoneEnumAmericaStVincent               TimezoneEnum = "America/St_Vincent"
	TimezoneEnumAmericaSwiftCurrent            TimezoneEnum = "America/Swift_Current"
	TimezoneEnumAmericaTegucigalpa             TimezoneEnum = "America/Tegucigalpa"
	TimezoneEnumAmericaThule                   TimezoneEnum = "America/Thule"
	TimezoneEnumAmericaThunderBay              TimezoneEnum = "America/Thunder_Bay"
	TimezoneEnumAmericaTijuana                 TimezoneEnum = "America/Tijuana"
	TimezoneEnumAmericaToronto                 TimezoneEnum = "America/Toronto"
	TimezoneEnumAmericaTortola                 TimezoneEnum = "America/Tortola"
	TimezoneEnumAmericaVancouver               TimezoneEnum = "America/Vancouver"
	TimezoneEnumAmericaVirgin                  TimezoneEnum = "America/Virgin"
	TimezoneEnumAmericaWhitehorse              TimezoneEnum = "America/Whitehorse"
	TimezoneEnumAmericaWinnipeg                TimezoneEnum = "America/Winnipeg"
	TimezoneEnumAmericaYakutat                 TimezoneEnum = "America/Yakutat"
	TimezoneEnumAmericaYellowknife             TimezoneEnum = "America/Yellowknife"
	TimezoneEnumAntarcticaCasey                TimezoneEnum = "Antarctica/Casey"
	TimezoneEnumAntarcticaDavis                TimezoneEnum = "Antarctica/Davis"
	TimezoneEnumAntarcticaDumontDUrville       TimezoneEnum = "Antarctica/DumontDUrville"
	TimezoneEnumAntarcticaMacquarie            TimezoneEnum = "Antarctica/Macquarie"
	TimezoneEnumAntarcticaMawson               TimezoneEnum = "Antarctica/Mawson"
	TimezoneEnumAntarcticaMcMurdo              TimezoneEnum = "Antarctica/McMurdo"
	TimezoneEnumAntarcticaPalmer               TimezoneEnum = "Antarctica/Palmer"
	TimezoneEnumAntarcticaRothera              TimezoneEnum = "Antarctica/Rothera"
	TimezoneEnumAntarcticaSouthPole            TimezoneEnum = "Antarctica/South_Pole"
	TimezoneEnumAntarcticaSyowa                TimezoneEnum = "Antarctica/Syowa"
	TimezoneEnumAntarcticaTroll                TimezoneEnum = "Antarctica/Troll"
	TimezoneEnumAntarcticaVostok               TimezoneEnum = "Antarctica/Vostok"
	TimezoneEnumArcticLongyearbyen             TimezoneEnum = "Arctic/Longyearbyen"
	TimezoneEnumAsiaAden                       TimezoneEnum = "Asia/Aden"
	TimezoneEnumAsiaAlmaty                     TimezoneEnum = "Asia/Almaty"
	TimezoneEnumAsiaAmman                      TimezoneEnum = "Asia/Amman"
	TimezoneEnumAsiaAnadyr                     TimezoneEnum = "Asia/Anadyr"
	TimezoneEnumAsiaAqtau                      TimezoneEnum = "Asia/Aqtau"
	TimezoneEnumAsiaAqtobe                     TimezoneEnum = "Asia/Aqtobe"
	TimezoneEnumAsiaAshgabat                   TimezoneEnum = "Asia/Ashgabat"
	TimezoneEnumAsiaAshkhabad                  TimezoneEnum = "Asia/Ashkhabad"
	TimezoneEnumAsiaAtyrau                     TimezoneEnum = "Asia/Atyrau"
	TimezoneEnumAsiaBaghdad                    TimezoneEnum = "Asia/Baghdad"
	TimezoneEnumAsiaBahrain                    TimezoneEnum = "Asia/Bahrain"
	TimezoneEnumAsiaBaku                       TimezoneEnum = "Asia/Baku"
	TimezoneEnumAsiaBangkok                    TimezoneEnum = "Asia/Bangkok"
	TimezoneEnumAsiaBarnaul                    TimezoneEnum = "Asia/Barnaul"
	TimezoneEnumAsiaBeirut                     TimezoneEnum = "Asia/Beirut"
	TimezoneEnumAsiaBishkek                    TimezoneEnum = "Asia/Bishkek"
	TimezoneEnumAsiaBrunei                     TimezoneEnum = "Asia/Brunei"
	TimezoneEnumAsiaCalcutta                   TimezoneEnum = "Asia/Calcutta"
	TimezoneEnumAsiaChita                      TimezoneEnum = "Asia/Chita"
	TimezoneEnumAsiaChoibalsan                 TimezoneEnum = "Asia/Choibalsan"
	TimezoneEnumAsiaChongqing                  TimezoneEnum = "Asia/Chongqing"
	TimezoneEnumAsiaChungking                  TimezoneEnum = "Asia/Chungking"
	TimezoneEnumAsiaColombo                    TimezoneEnum = "Asia/Colombo"
	TimezoneEnumAsiaDacca                      TimezoneEnum = "Asia/Dacca"
	TimezoneEnumAsiaDamascus                   TimezoneEnum = "Asia/Damascus"
	TimezoneEnumAsiaDhaka                      TimezoneEnum = "Asia/Dhaka"
	TimezoneEnumAsiaDili                       TimezoneEnum = "Asia/Dili"
	TimezoneEnumAsiaDubai                      TimezoneEnum = "Asia/Dubai"
	TimezoneEnumAsiaDushanbe                   TimezoneEnum = "Asia/Dushanbe"
	TimezoneEnumAsiaFamagusta                  TimezoneEnum = "Asia/Famagusta"
	TimezoneEnumAsiaGaza                       TimezoneEnum = "Asia/Gaza"
	TimezoneEnumAsiaHarbin                     TimezoneEnum = "Asia/Harbin"
	TimezoneEnumAsiaHebron                     TimezoneEnum = "Asia/Hebron"
	TimezoneEnumAsiaHoChiMinh                  TimezoneEnum = "Asia/Ho_Chi_Minh"
	TimezoneEnumAsiaHongKong                   TimezoneEnum = "Asia/Hong_Kong"
	TimezoneEnumAsiaHovd                       TimezoneEnum = "Asia/Hovd"
	TimezoneEnumAsiaIrkutsk                    TimezoneEnum = "Asia/Irkutsk"
	TimezoneEnumAsiaIstanbul                   TimezoneEnum = "Asia/Istanbul"
	TimezoneEnumAsiaJakarta                    TimezoneEnum = "Asia/Jakarta"
	TimezoneEnumAsiaJayapura                   TimezoneEnum = "Asia/Jayapura"
	TimezoneEnumAsiaJerusalem                  TimezoneEnum = "Asia/Jerusalem"
	TimezoneEnumAsiaKabul                      TimezoneEnum = "Asia/Kabul"
	TimezoneEnumAsiaKamchatka                  TimezoneEnum = "Asia/Kamchatka"
	TimezoneEnumAsiaKarachi                    TimezoneEnum = "Asia/Karachi"
	TimezoneEnumAsiaKashgar                    TimezoneEnum = "Asia/Kashgar"
	TimezoneEnumAsiaKathmandu                  TimezoneEnum = "Asia/Kathmandu"
	TimezoneEnumAsiaKatmandu                   TimezoneEnum = "Asia/Katmandu"
	TimezoneEnumAsiaKhandyga                   TimezoneEnum = "Asia/Khandyga"
	TimezoneEnumAsiaKolkata                    TimezoneEnum = "Asia/Kolkata"
	TimezoneEnumAsiaKrasnoyarsk                TimezoneEnum = "Asia/Krasnoyarsk"
	TimezoneEnumAsiaKualaLumpur                TimezoneEnum = "Asia/Kuala_Lumpur"
	TimezoneEnumAsiaKuching                    TimezoneEnum = "Asia/Kuching"
	TimezoneEnumAsiaKuwait                     TimezoneEnum = "Asia/Kuwait"
	TimezoneEnumAsiaMacao                      TimezoneEnum = "Asia/Macao"
	TimezoneEnumAsiaMacau                      TimezoneEnum = "Asia/Macau"
	TimezoneEnumAsiaMagadan                    TimezoneEnum = "Asia/Magadan"
	TimezoneEnumAsiaMakassar                   TimezoneEnum = "Asia/Makassar"
	TimezoneEnumAsiaManila                     TimezoneEnum = "Asia/Manila"
	TimezoneEnumAsiaMuscat                     TimezoneEnum = "Asia/Muscat"
	TimezoneEnumAsiaNicosia                    TimezoneEnum = "Asia/Nicosia"
	TimezoneEnumAsiaNovokuznetsk               TimezoneEnum = "Asia/Novokuznetsk"
	TimezoneEnumAsiaNovosibirsk                TimezoneEnum = "Asia/Novosibirsk"
	TimezoneEnumAsiaOmsk                       TimezoneEnum = "Asia/Omsk"
	TimezoneEnumAsiaOral                       TimezoneEnum = "Asia/Oral"
	TimezoneEnumAsiaPhnomPenh                  TimezoneEnum = "Asia/Phnom_Penh"
	TimezoneEnumAsiaPontianak                  TimezoneEnum = "Asia/Pontianak"
	TimezoneEnumAsiaPyongyang                  TimezoneEnum = "Asia/Pyongyang"
	TimezoneEnumAsiaQatar                      TimezoneEnum = "Asia/Qatar"
	TimezoneEnumAsiaQostanay                   TimezoneEnum = "Asia/Qostanay"
	TimezoneEnumAsiaQyzylorda                  TimezoneEnum = "Asia/Qyzylorda"
	TimezoneEnumAsiaRangoon                    TimezoneEnum = "Asia/Rangoon"
	TimezoneEnumAsiaRiyadh                     TimezoneEnum = "Asia/Riyadh"
	TimezoneEnumAsiaSaigon                     TimezoneEnum = "Asia/Saigon"
	TimezoneEnumAsiaSakhalin                   TimezoneEnum = "Asia/Sakhalin"
	TimezoneEnumAsiaSamarkand                  TimezoneEnum = "Asia/Samarkand"
	TimezoneEnumAsiaSeoul                      TimezoneEnum = "Asia/Seoul"
	TimezoneEnumAsiaShanghai                   TimezoneEnum = "Asia/Shanghai"
	TimezoneEnumAsiaSingapore                  TimezoneEnum = "Asia/Singapore"
	TimezoneEnumAsiaSrednekolymsk              TimezoneEnum = "Asia/Srednekolymsk"
	TimezoneEnumAsiaTaipei                     TimezoneEnum = "Asia/Taipei"
	TimezoneEnumAsiaTashkent                   TimezoneEnum = "Asia/Tashkent"
	TimezoneEnumAsiaTbilisi                    TimezoneEnum = "Asia/Tbilisi"
	TimezoneEnumAsiaTehran                     TimezoneEnum = "Asia/Tehran"
	TimezoneEnumAsiaTelAviv                    TimezoneEnum = "Asia/Tel_Aviv"
	TimezoneEnumAsiaThimbu                     TimezoneEnum = "Asia/Thimbu"
	TimezoneEnumAsiaThimphu                    TimezoneEnum = "Asia/Thimphu"
	TimezoneEnumAsiaTokyo                      TimezoneEnum = "Asia/Tokyo"
	TimezoneEnumAsiaTomsk                      TimezoneEnum = "Asia/Tomsk"
	TimezoneEnumAsiaUjungPandang               TimezoneEnum = "Asia/Ujung_Pandang"
	TimezoneEnumAsiaUlaanbaatar                TimezoneEnum = "Asia/Ulaanbaatar"
	TimezoneEnumAsiaUlanBator                  TimezoneEnum = "Asia/Ulan_Bator"
	TimezoneEnumAsiaUrumqi                     TimezoneEnum = "Asia/Urumqi"
	TimezoneEnumAsiaUstNera                    TimezoneEnum = "Asia/Ust-Nera"
	TimezoneEnumAsiaVientiane                  TimezoneEnum = "Asia/Vientiane"
	TimezoneEnumAsiaVladivostok                TimezoneEnum = "Asia/Vladivostok"
	TimezoneEnumAsiaYakutsk                    TimezoneEnum = "Asia/Yakutsk"
	TimezoneEnumAsiaYangon                     TimezoneEnum = "Asia/Yangon"
	TimezoneEnumAsiaYekaterinburg              TimezoneEnum = "Asia/Yekaterinburg"
	TimezoneEnumAsiaYerevan                    TimezoneEnum = "Asia/Yerevan"
	TimezoneEnumAtlanticAzores                 TimezoneEnum = "Atlantic/Azores"
	TimezoneEnumAtlanticBermuda                TimezoneEnum = "Atlantic/Bermuda"
	TimezoneEnumAtlanticCanary                 TimezoneEnum = "Atlantic/Canary"
	TimezoneEnumAtlanticCapeVerde              TimezoneEnum = "Atlantic/Cape_Verde"
	TimezoneEnumAtlanticFaeroe                 TimezoneEnum = "Atlantic/Faeroe"
	TimezoneEnumAtlanticFaroe                  TimezoneEnum = "Atlantic/Faroe"
	TimezoneEnumAtlanticJanMayen               TimezoneEnum = "Atlantic/Jan_Mayen"
	TimezoneEnumAtlanticMadeira                TimezoneEnum = "Atlantic/Madeira"
	TimezoneEnumAtlanticReykjavik              TimezoneEnum = "Atlantic/Reykjavik"
	TimezoneEnumAtlanticSouthGeorgia           TimezoneEnum = "Atlantic/South_Georgia"
	TimezoneEnumAtlanticStHelena               TimezoneEnum = "Atlantic/St_Helena"
	TimezoneEnumAtlanticStanley                TimezoneEnum = "Atlantic/Stanley"
	TimezoneEnumAustraliaAct                   TimezoneEnum = "Australia/ACT"
	TimezoneEnumAustraliaAdelaide              TimezoneEnum = "Australia/Adelaide"
	TimezoneEnumAustraliaBrisbane              TimezoneEnum = "Australia/Brisbane"
	TimezoneEnumAustraliaBrokenHill            TimezoneEnum = "Australia/Broken_Hill"
	TimezoneEnumAustraliaCanberra              TimezoneEnum = "Australia/Canberra"
	TimezoneEnumAustraliaCurrie                TimezoneEnum = "Australia/Currie"
	TimezoneEnumAustraliaDarwin                TimezoneEnum = "Australia/Darwin"
	TimezoneEnumAustraliaEucla                 TimezoneEnum = "Australia/Eucla"
	TimezoneEnumAustraliaHobart                TimezoneEnum = "Australia/Hobart"
	TimezoneEnumAustraliaLhi                   TimezoneEnum = "Australia/LHI"
	TimezoneEnumAustraliaLindeman              TimezoneEnum = "Australia/Lindeman"
	TimezoneEnumAustraliaLordHowe              TimezoneEnum = "Australia/Lord_Howe"
	TimezoneEnumAustraliaMelbourne             TimezoneEnum = "Australia/Melbourne"
	TimezoneEnumAustraliaNsw                   TimezoneEnum = "Australia/NSW"
	TimezoneEnumAustraliaNorth                 TimezoneEnum = "Australia/North"
	TimezoneEnumAustraliaPerth                 TimezoneEnum = "Australia/Perth"
	TimezoneEnumAustraliaQueensland            TimezoneEnum = "Australia/Queensland"
	TimezoneEnumAustraliaSouth                 TimezoneEnum = "Australia/South"
	TimezoneEnumAustraliaSydney                TimezoneEnum = "Australia/Sydney"
	TimezoneEnumAustraliaTasmania              TimezoneEnum = "Australia/Tasmania"
	TimezoneEnumAustraliaVictoria              TimezoneEnum = "Australia/Victoria"
	TimezoneEnumAustraliaWest                  TimezoneEnum = "Australia/West"
	TimezoneEnumAustraliaYancowinna            TimezoneEnum = "Australia/Yancowinna"
	TimezoneEnumBrazilAcre                     TimezoneEnum = "Brazil/Acre"
	TimezoneEnumBrazilDeNoronha                TimezoneEnum = "Brazil/DeNoronha"
	TimezoneEnumBrazilEast                     TimezoneEnum = "Brazil/East"
	TimezoneEnumBrazilWest                     TimezoneEnum = "Brazil/West"
	TimezoneEnumCet                            TimezoneEnum = "CET"
	TimezoneEnumCst6Cdt                        TimezoneEnum = "CST6CDT"
	TimezoneEnumCanadaAtlantic                 TimezoneEnum = "Canada/Atlantic"
	TimezoneEnumCanadaCentral                  TimezoneEnum = "Canada/Central"
	TimezoneEnumCanadaEastern                  TimezoneEnum = "Canada/Eastern"
	TimezoneEnumCanadaMountain                 TimezoneEnum = "Canada/Mountain"
	TimezoneEnumCanadaNewfoundland             TimezoneEnum = "Canada/Newfoundland"
	TimezoneEnumCanadaPacific                  TimezoneEnum = "Canada/Pacific"
	TimezoneEnumCanadaSaskatchewan             TimezoneEnum = "Canada/Saskatchewan"
	TimezoneEnumCanadaYukon                    TimezoneEnum = "Canada/Yukon"
	TimezoneEnumChileContinental               TimezoneEnum = "Chile/Continental"
	TimezoneEnumChileEasterIsland              TimezoneEnum = "Chile/EasterIsland"
	TimezoneEnumCuba                           TimezoneEnum = "Cuba"
	TimezoneEnumEet                            TimezoneEnum = "EET"
	TimezoneEnumEst                            TimezoneEnum = "EST"
	TimezoneEnumEst5Edt                        TimezoneEnum = "EST5EDT"
	TimezoneEnumEgypt                          TimezoneEnum = "Egypt"
	TimezoneEnumEire                           TimezoneEnum = "Eire"
	TimezoneEnumEtcGmt                         TimezoneEnum = "Etc/GMT"
	TimezoneEnumEtcGmtPlus0                    TimezoneEnum = "Etc/GMT+0"
	TimezoneEnumEtcGmtPlus1                    TimezoneEnum = "Etc/GMT+1"
	TimezoneEnumEtcGmtPlus10                   TimezoneEnum = "Etc/GMT+10"
	TimezoneEnumEtcGmtPlus11                   TimezoneEnum = "Etc/GMT+11"
	TimezoneEnumEtcGmtPlus12                   TimezoneEnum = "Etc/GMT+12"
	TimezoneEnumEtcGmtPlus2                    TimezoneEnum = "Etc/GMT+2"
	TimezoneEnumEtcGmtPlus3                    TimezoneEnum = "Etc/GMT+3"
	TimezoneEnumEtcGmtPlus4                    TimezoneEnum = "Etc/GMT+4"
	TimezoneEnumEtcGmtPlus5                    TimezoneEnum = "Etc/GMT+5"
	TimezoneEnumEtcGmtPlus6                    TimezoneEnum = "Etc/GMT+6"
	TimezoneEnumEtcGmtPlus7                    TimezoneEnum = "Etc/GMT+7"
	TimezoneEnumEtcGmtPlus8                    TimezoneEnum = "Etc/GMT+8"
	TimezoneEnumEtcGmtPlus9                    TimezoneEnum = "Etc/GMT+9"
	TimezoneEnumEtcGmt0                        TimezoneEnum = "Etc/GMT-0"
	TimezoneEnumEtcGmt1                        TimezoneEnum = "Etc/GMT-1"
	TimezoneEnumEtcGmt10                       TimezoneEnum = "Etc/GMT-10"
	TimezoneEnumEtcGmt11                       TimezoneEnum = "Etc/GMT-11"
	TimezoneEnumEtcGmt12                       TimezoneEnum = "Etc/GMT-12"
	TimezoneEnumEtcGmt13                       TimezoneEnum = "Etc/GMT-13"
	TimezoneEnumEtcGmt14                       TimezoneEnum = "Etc/GMT-14"
	TimezoneEnumEtcGmt2                        TimezoneEnum = "Etc/GMT-2"
	TimezoneEnumEtcGmt3                        TimezoneEnum = "Etc/GMT-3"
	TimezoneEnumEtcGmt4                        TimezoneEnum = "Etc/GMT-4"
	TimezoneEnumEtcGmt5                        TimezoneEnum = "Etc/GMT-5"
	TimezoneEnumEtcGmt6                        TimezoneEnum = "Etc/GMT-6"
	TimezoneEnumEtcGmt7                        TimezoneEnum = "Etc/GMT-7"
	TimezoneEnumEtcGmt8                        TimezoneEnum = "Etc/GMT-8"
	TimezoneEnumEtcGmt9                        TimezoneEnum = "Etc/GMT-9"
	TimezoneEnumEtcGreenwich                   TimezoneEnum = "Etc/Greenwich"
	TimezoneEnumEtcUct                         TimezoneEnum = "Etc/UCT"
	TimezoneEnumEtcUtc                         TimezoneEnum = "Etc/UTC"
	TimezoneEnumEtcUniversal                   TimezoneEnum = "Etc/Universal"
	TimezoneEnumEtcZulu                        TimezoneEnum = "Etc/Zulu"
	TimezoneEnumEuropeAmsterdam                TimezoneEnum = "Europe/Amsterdam"
	TimezoneEnumEuropeAndorra                  TimezoneEnum = "Europe/Andorra"
	TimezoneEnumEuropeAstrakhan                TimezoneEnum = "Europe/Astrakhan"
	TimezoneEnumEuropeAthens                   TimezoneEnum = "Europe/Athens"
	TimezoneEnumEuropeBelfast                  TimezoneEnum = "Europe/Belfast"
	TimezoneEnumEuropeBelgrade                 TimezoneEnum = "Europe/Belgrade"
	TimezoneEnumEuropeBerlin                   TimezoneEnum = "Europe/Berlin"
	TimezoneEnumEuropeBratislava               TimezoneEnum = "Europe/Bratislava"
	TimezoneEnumEuropeBrussels                 TimezoneEnum = "Europe/Brussels"
	TimezoneEnumEuropeBucharest                TimezoneEnum = "Europe/Bucharest"
	TimezoneEnumEuropeBudapest                 TimezoneEnum = "Europe/Budapest"
	TimezoneEnumEuropeBusingen                 TimezoneEnum = "Europe/Busingen"
	TimezoneEnumEuropeChisinau                 TimezoneEnum = "Europe/Chisinau"
	TimezoneEnumEuropeCopenhagen               TimezoneEnum = "Europe/Copenhagen"
	TimezoneEnumEuropeDublin                   TimezoneEnum = "Europe/Dublin"
	TimezoneEnumEuropeGibraltar                TimezoneEnum = "Europe/Gibraltar"
	TimezoneEnumEuropeGuernsey                 TimezoneEnum = "Europe/Guernsey"
	TimezoneEnumEuropeHelsinki                 TimezoneEnum = "Europe/Helsinki"
	TimezoneEnumEuropeIsleOfMan                TimezoneEnum = "Europe/Isle_of_Man"
	TimezoneEnumEuropeIstanbul                 TimezoneEnum = "Europe/Istanbul"
	TimezoneEnumEuropeJersey                   TimezoneEnum = "Europe/Jersey"
	TimezoneEnumEuropeKaliningrad              TimezoneEnum = "Europe/Kaliningrad"
	TimezoneEnumEuropeKiev                     TimezoneEnum = "Europe/Kiev"
	TimezoneEnumEuropeKirov                    TimezoneEnum = "Europe/Kirov"
	TimezoneEnumEuropeLisbon                   TimezoneEnum = "Europe/Lisbon"
	TimezoneEnumEuropeLjubljana                TimezoneEnum = "Europe/Ljubljana"
	TimezoneEnumEuropeLondon                   TimezoneEnum = "Europe/London"
	TimezoneEnumEuropeLuxembourg               TimezoneEnum = "Europe/Luxembourg"
	TimezoneEnumEuropeMadrid                   TimezoneEnum = "Europe/Madrid"
	TimezoneEnumEuropeMalta                    TimezoneEnum = "Europe/Malta"
	TimezoneEnumEuropeMariehamn                TimezoneEnum = "Europe/Mariehamn"
	TimezoneEnumEuropeMinsk                    TimezoneEnum = "Europe/Minsk"
	TimezoneEnumEuropeMonaco                   TimezoneEnum = "Europe/Monaco"
	TimezoneEnumEuropeMoscow                   TimezoneEnum = "Europe/Moscow"
	TimezoneEnumEuropeNicosia                  TimezoneEnum = "Europe/Nicosia"
	TimezoneEnumEuropeOslo                     TimezoneEnum = "Europe/Oslo"
	TimezoneEnumEuropeParis                    TimezoneEnum = "Europe/Paris"
	TimezoneEnumEuropePodgorica                TimezoneEnum = "Europe/Podgorica"
	TimezoneEnumEuropePrague                   TimezoneEnum = "Europe/Prague"
	TimezoneEnumEuropeRiga                     TimezoneEnum = "Europe/Riga"
	TimezoneEnumEuropeRome                     TimezoneEnum = "Europe/Rome"
	TimezoneEnumEuropeSamara                   TimezoneEnum = "Europe/Samara"
	TimezoneEnumEuropeSanMarino                TimezoneEnum = "Europe/San_Marino"
	TimezoneEnumEuropeSarajevo                 TimezoneEnum = "Europe/Sarajevo"
	TimezoneEnumEuropeSaratov                  TimezoneEnum = "Europe/Saratov"
	TimezoneEnumEuropeSimferopol               TimezoneEnum = "Europe/Simferopol"
	TimezoneEnumEuropeSkopje                   TimezoneEnum = "Europe/Skopje"
	TimezoneEnumEuropeSofia                    TimezoneEnum = "Europe/Sofia"
	TimezoneEnumEuropeStockholm                TimezoneEnum = "Europe/Stockholm"
	TimezoneEnumEuropeTallinn                  TimezoneEnum = "Europe/Tallinn"
	TimezoneEnumEuropeTirane                   TimezoneEnum = "Europe/Tirane"
	TimezoneEnumEuropeTiraspol                 TimezoneEnum = "Europe/Tiraspol"
	TimezoneEnumEuropeUlyanovsk                TimezoneEnum = "Europe/Ulyanovsk"
	TimezoneEnumEuropeUzhgorod                 TimezoneEnum = "Europe/Uzhgorod"
	TimezoneEnumEuropeVaduz                    TimezoneEnum = "Europe/Vaduz"
	TimezoneEnumEuropeVatican                  TimezoneEnum = "Europe/Vatican"
	TimezoneEnumEuropeVienna                   TimezoneEnum = "Europe/Vienna"
	TimezoneEnumEuropeVilnius                  TimezoneEnum = "Europe/Vilnius"
	TimezoneEnumEuropeVolgograd                TimezoneEnum = "Europe/Volgograd"
	TimezoneEnumEuropeWarsaw                   TimezoneEnum = "Europe/Warsaw"
	TimezoneEnumEuropeZagreb                   TimezoneEnum = "Europe/Zagreb"
	TimezoneEnumEuropeZaporozhye               TimezoneEnum = "Europe/Zaporozhye"
	TimezoneEnumEuropeZurich                   TimezoneEnum = "Europe/Zurich"
	TimezoneEnumGb                             TimezoneEnum = "GB"
	TimezoneEnumGbEire                         TimezoneEnum = "GB-Eire"
	TimezoneEnumGmt                            TimezoneEnum = "GMT"
	TimezoneEnumGmtPlus0                       TimezoneEnum = "GMT+0"
	TimezoneEnumGmt0                           TimezoneEnum = "GMT-0"
	TimezoneEnumGreenwich                      TimezoneEnum = "Greenwich"
	TimezoneEnumHst                            TimezoneEnum = "HST"
	TimezoneEnumHongkong                       TimezoneEnum = "Hongkong"
	TimezoneEnumIceland                        TimezoneEnum = "Iceland"
	TimezoneEnumIndianAntananarivo             TimezoneEnum = "Indian/Antananarivo"
	TimezoneEnumIndianChagos                   TimezoneEnum = "Indian/Chagos"
	TimezoneEnumIndianChristmas                TimezoneEnum = "Indian/Christmas"
	TimezoneEnumIndianCocos                    TimezoneEnum = "Indian/Cocos"
	TimezoneEnumIndianComoro                   TimezoneEnum = "Indian/Comoro"
	TimezoneEnumIndianKerguelen                TimezoneEnum = "Indian/Kerguelen"
	TimezoneEnumIndianMahe                     TimezoneEnum = "Indian/Mahe"
	TimezoneEnumIndianMaldives                 TimezoneEnum = "Indian/Maldives"
	TimezoneEnumIndianMauritius                TimezoneEnum = "Indian/Mauritius"
	TimezoneEnumIndianMayotte                  TimezoneEnum = "Indian/Mayotte"
	TimezoneEnumIndianReunion                  TimezoneEnum = "Indian/Reunion"
	TimezoneEnumIran                           TimezoneEnum = "Iran"
	TimezoneEnumIsrael                         TimezoneEnum = "Israel"
	TimezoneEnumJamaica                        TimezoneEnum = "Jamaica"
	TimezoneEnumJapan                          TimezoneEnum = "Japan"
	TimezoneEnumKwajalein                      TimezoneEnum = "Kwajalein"
	TimezoneEnumLibya                          TimezoneEnum = "Libya"
	TimezoneEnumMet                            TimezoneEnum = "MET"
	TimezoneEnumMst                            TimezoneEnum = "MST"
	TimezoneEnumMst7Mdt                        TimezoneEnum = "MST7MDT"
	TimezoneEnumMexicoBajaNorte                TimezoneEnum = "Mexico/BajaNorte"
	TimezoneEnumMexicoBajaSur                  TimezoneEnum = "Mexico/BajaSur"
	TimezoneEnumMexicoGeneral                  TimezoneEnum = "Mexico/General"
	TimezoneEnumNz                             TimezoneEnum = "NZ"
	TimezoneEnumNzChat                         TimezoneEnum = "NZ-CHAT"
	TimezoneEnumNavajo                         TimezoneEnum = "Navajo"
	TimezoneEnumPrc                            TimezoneEnum = "PRC"
	TimezoneEnumPst8Pdt                        TimezoneEnum = "PST8PDT"
	TimezoneEnumPacificApia                    TimezoneEnum = "Pacific/Apia"
	TimezoneEnumPacificAuckland                TimezoneEnum = "Pacific/Auckland"
	TimezoneEnumPacificBougainville            TimezoneEnum = "Pacific/Bougainville"
	TimezoneEnumPacificChatham                 TimezoneEnum = "Pacific/Chatham"
	TimezoneEnumPacificChuuk                   TimezoneEnum = "Pacific/Chuuk"
	TimezoneEnumPacificEaster                  TimezoneEnum = "Pacific/Easter"
	TimezoneEnumPacificEfate                   TimezoneEnum = "Pacific/Efate"
	TimezoneEnumPacificEnderbury               TimezoneEnum = "Pacific/Enderbury"
	TimezoneEnumPacificFakaofo                 TimezoneEnum = "Pacific/Fakaofo"
	TimezoneEnumPacificFiji                    TimezoneEnum = "Pacific/Fiji"
	TimezoneEnumPacificFunafuti                TimezoneEnum = "Pacific/Funafuti"
	TimezoneEnumPacificGalapagos               TimezoneEnum = "Pacific/Galapagos"
	TimezoneEnumPacificGambier                 TimezoneEnum = "Pacific/Gambier"
	TimezoneEnumPacificGuadalcanal             TimezoneEnum = "Pacific/Guadalcanal"
	TimezoneEnumPacificGuam                    TimezoneEnum = "Pacific/Guam"
	TimezoneEnumPacificHonolulu                TimezoneEnum = "Pacific/Honolulu"
	TimezoneEnumPacificJohnston                TimezoneEnum = "Pacific/Johnston"
	TimezoneEnumPacificKanton                  TimezoneEnum = "Pacific/Kanton"
	TimezoneEnumPacificKiritimati              TimezoneEnum = "Pacific/Kiritimati"
	TimezoneEnumPacificKosrae                  TimezoneEnum = "Pacific/Kosrae"
	TimezoneEnumPacificKwajalein               TimezoneEnum = "Pacific/Kwajalein"
	TimezoneEnumPacificMajuro                  TimezoneEnum = "Pacific/Majuro"
	TimezoneEnumPacificMarquesas               TimezoneEnum = "Pacific/Marquesas"
	TimezoneEnumPacificMidway                  TimezoneEnum = "Pacific/Midway"
	TimezoneEnumPacificNauru                   TimezoneEnum = "Pacific/Nauru"
	TimezoneEnumPacificNiue                    TimezoneEnum = "Pacific/Niue"
	TimezoneEnumPacificNorfolk                 TimezoneEnum = "Pacific/Norfolk"
	TimezoneEnumPacificNoumea                  TimezoneEnum = "Pacific/Noumea"
	TimezoneEnumPacificPagoPago                TimezoneEnum = "Pacific/Pago_Pago"
	TimezoneEnumPacificPalau                   TimezoneEnum = "Pacific/Palau"
	TimezoneEnumPacificPitcairn                TimezoneEnum = "Pacific/Pitcairn"
	TimezoneEnumPacificPohnpei                 TimezoneEnum = "Pacific/Pohnpei"
	TimezoneEnumPacificPonape                  TimezoneEnum = "Pacific/Ponape"
	TimezoneEnumPacificPortMoresby             TimezoneEnum = "Pacific/Port_Moresby"
	TimezoneEnumPacificRarotonga               TimezoneEnum = "Pacific/Rarotonga"
	TimezoneEnumPacificSaipan                  TimezoneEnum = "Pacific/Saipan"
	TimezoneEnumPacificSamoa                   TimezoneEnum = "Pacific/Samoa"
	TimezoneEnumPacificTahiti                  TimezoneEnum = "Pacific/Tahiti"
	TimezoneEnumPacificTarawa                  TimezoneEnum = "Pacific/Tarawa"
	TimezoneEnumPacificTongatapu               TimezoneEnum = "Pacific/Tongatapu"
	TimezoneEnumPacificTruk                    TimezoneEnum = "Pacific/Truk"
	TimezoneEnumPacificWake                    TimezoneEnum = "Pacific/Wake"
	TimezoneEnumPacificWallis                  TimezoneEnum = "Pacific/Wallis"
	TimezoneEnumPacificYap                     TimezoneEnum = "Pacific/Yap"
	TimezoneEnumPoland                         TimezoneEnum = "Poland"
	TimezoneEnumPortugal                       TimezoneEnum = "Portugal"
	TimezoneEnumRoc                            TimezoneEnum = "ROC"
	TimezoneEnumRok                            TimezoneEnum = "ROK"
	TimezoneEnumSingapore                      TimezoneEnum = "Singapore"
	TimezoneEnumTurkey                         TimezoneEnum = "Turkey"
	TimezoneEnumUct                            TimezoneEnum = "UCT"
	TimezoneEnumUsAlaska                       TimezoneEnum = "US/Alaska"
	TimezoneEnumUsAleutian                     TimezoneEnum = "US/Aleutian"
	TimezoneEnumUsArizona                      TimezoneEnum = "US/Arizona"
	TimezoneEnumUsCentral                      TimezoneEnum = "US/Central"
	TimezoneEnumUsEastIndiana                  TimezoneEnum = "US/East-Indiana"
	TimezoneEnumUsEastern                      TimezoneEnum = "US/Eastern"
	TimezoneEnumUsHawaii                       TimezoneEnum = "US/Hawaii"
	TimezoneEnumUsIndianaStarke                TimezoneEnum = "US/Indiana-Starke"
	TimezoneEnumUsMichigan                     TimezoneEnum = "US/Michigan"
	TimezoneEnumUsMountain                     TimezoneEnum = "US/Mountain"
	TimezoneEnumUsPacific                      TimezoneEnum = "US/Pacific"
	TimezoneEnumUsSamoa                        TimezoneEnum = "US/Samoa"
	TimezoneEnumUtc                            TimezoneEnum = "UTC"
	TimezoneEnumUniversal                      TimezoneEnum = "Universal"
	TimezoneEnumWSu                            TimezoneEnum = "W-SU"
	TimezoneEnumWet                            TimezoneEnum = "WET"
	TimezoneEnumZulu                           TimezoneEnum = "Zulu"
)

func (e TimezoneEnum) ToPointer() *TimezoneEnum {
	return &e
}

func (e *TimezoneEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Africa/Abidjan":
		fallthrough
	case "Africa/Accra":
		fallthrough
	case "Africa/Addis_Ababa":
		fallthrough
	case "Africa/Algiers":
		fallthrough
	case "Africa/Asmara":
		fallthrough
	case "Africa/Asmera":
		fallthrough
	case "Africa/Bamako":
		fallthrough
	case "Africa/Bangui":
		fallthrough
	case "Africa/Banjul":
		fallthrough
	case "Africa/Bissau":
		fallthrough
	case "Africa/Blantyre":
		fallthrough
	case "Africa/Brazzaville":
		fallthrough
	case "Africa/Bujumbura":
		fallthrough
	case "Africa/Cairo":
		fallthrough
	case "Africa/Casablanca":
		fallthrough
	case "Africa/Ceuta":
		fallthrough
	case "Africa/Conakry":
		fallthrough
	case "Africa/Dakar":
		fallthrough
	case "Africa/Dar_es_Salaam":
		fallthrough
	case "Africa/Djibouti":
		fallthrough
	case "Africa/Douala":
		fallthrough
	case "Africa/El_Aaiun":
		fallthrough
	case "Africa/Freetown":
		fallthrough
	case "Africa/Gaborone":
		fallthrough
	case "Africa/Harare":
		fallthrough
	case "Africa/Johannesburg":
		fallthrough
	case "Africa/Juba":
		fallthrough
	case "Africa/Kampala":
		fallthrough
	case "Africa/Khartoum":
		fallthrough
	case "Africa/Kigali":
		fallthrough
	case "Africa/Kinshasa":
		fallthrough
	case "Africa/Lagos":
		fallthrough
	case "Africa/Libreville":
		fallthrough
	case "Africa/Lome":
		fallthrough
	case "Africa/Luanda":
		fallthrough
	case "Africa/Lubumbashi":
		fallthrough
	case "Africa/Lusaka":
		fallthrough
	case "Africa/Malabo":
		fallthrough
	case "Africa/Maputo":
		fallthrough
	case "Africa/Maseru":
		fallthrough
	case "Africa/Mbabane":
		fallthrough
	case "Africa/Mogadishu":
		fallthrough
	case "Africa/Monrovia":
		fallthrough
	case "Africa/Nairobi":
		fallthrough
	case "Africa/Ndjamena":
		fallthrough
	case "Africa/Niamey":
		fallthrough
	case "Africa/Nouakchott":
		fallthrough
	case "Africa/Ouagadougou":
		fallthrough
	case "Africa/Porto-Novo":
		fallthrough
	case "Africa/Sao_Tome":
		fallthrough
	case "Africa/Timbuktu":
		fallthrough
	case "Africa/Tripoli":
		fallthrough
	case "Africa/Tunis":
		fallthrough
	case "Africa/Windhoek":
		fallthrough
	case "America/Adak":
		fallthrough
	case "America/Anchorage":
		fallthrough
	case "America/Anguilla":
		fallthrough
	case "America/Antigua":
		fallthrough
	case "America/Araguaina":
		fallthrough
	case "America/Argentina/Buenos_Aires":
		fallthrough
	case "America/Argentina/Catamarca":
		fallthrough
	case "America/Argentina/ComodRivadavia":
		fallthrough
	case "America/Argentina/Cordoba":
		fallthrough
	case "America/Argentina/Jujuy":
		fallthrough
	case "America/Argentina/La_Rioja":
		fallthrough
	case "America/Argentina/Mendoza":
		fallthrough
	case "America/Argentina/Rio_Gallegos":
		fallthrough
	case "America/Argentina/Salta":
		fallthrough
	case "America/Argentina/San_Juan":
		fallthrough
	case "America/Argentina/San_Luis":
		fallthrough
	case "America/Argentina/Tucuman":
		fallthrough
	case "America/Argentina/Ushuaia":
		fallthrough
	case "America/Aruba":
		fallthrough
	case "America/Asuncion":
		fallthrough
	case "America/Atikokan":
		fallthrough
	case "America/Atka":
		fallthrough
	case "America/Bahia":
		fallthrough
	case "America/Bahia_Banderas":
		fallthrough
	case "America/Barbados":
		fallthrough
	case "America/Belem":
		fallthrough
	case "America/Belize":
		fallthrough
	case "America/Blanc-Sablon":
		fallthrough
	case "America/Boa_Vista":
		fallthrough
	case "America/Bogota":
		fallthrough
	case "America/Boise":
		fallthrough
	case "America/Buenos_Aires":
		fallthrough
	case "America/Cambridge_Bay":
		fallthrough
	case "America/Campo_Grande":
		fallthrough
	case "America/Cancun":
		fallthrough
	case "America/Caracas":
		fallthrough
	case "America/Catamarca":
		fallthrough
	case "America/Cayenne":
		fallthrough
	case "America/Cayman":
		fallthrough
	case "America/Chicago":
		fallthrough
	case "America/Chihuahua":
		fallthrough
	case "America/Coral_Harbour":
		fallthrough
	case "America/Cordoba":
		fallthrough
	case "America/Costa_Rica":
		fallthrough
	case "America/Creston":
		fallthrough
	case "America/Cuiaba":
		fallthrough
	case "America/Curacao":
		fallthrough
	case "America/Danmarkshavn":
		fallthrough
	case "America/Dawson":
		fallthrough
	case "America/Dawson_Creek":
		fallthrough
	case "America/Denver":
		fallthrough
	case "America/Detroit":
		fallthrough
	case "America/Dominica":
		fallthrough
	case "America/Edmonton":
		fallthrough
	case "America/Eirunepe":
		fallthrough
	case "America/El_Salvador":
		fallthrough
	case "America/Ensenada":
		fallthrough
	case "America/Fort_Nelson":
		fallthrough
	case "America/Fort_Wayne":
		fallthrough
	case "America/Fortaleza":
		fallthrough
	case "America/Glace_Bay":
		fallthrough
	case "America/Godthab":
		fallthrough
	case "America/Goose_Bay":
		fallthrough
	case "America/Grand_Turk":
		fallthrough
	case "America/Grenada":
		fallthrough
	case "America/Guadeloupe":
		fallthrough
	case "America/Guatemala":
		fallthrough
	case "America/Guayaquil":
		fallthrough
	case "America/Guyana":
		fallthrough
	case "America/Halifax":
		fallthrough
	case "America/Havana":
		fallthrough
	case "America/Hermosillo":
		fallthrough
	case "America/Indiana/Indianapolis":
		fallthrough
	case "America/Indiana/Knox":
		fallthrough
	case "America/Indiana/Marengo":
		fallthrough
	case "America/Indiana/Petersburg":
		fallthrough
	case "America/Indiana/Tell_City":
		fallthrough
	case "America/Indiana/Vevay":
		fallthrough
	case "America/Indiana/Vincennes":
		fallthrough
	case "America/Indiana/Winamac":
		fallthrough
	case "America/Indianapolis":
		fallthrough
	case "America/Inuvik":
		fallthrough
	case "America/Iqaluit":
		fallthrough
	case "America/Jamaica":
		fallthrough
	case "America/Jujuy":
		fallthrough
	case "America/Juneau":
		fallthrough
	case "America/Kentucky/Louisville":
		fallthrough
	case "America/Kentucky/Monticello":
		fallthrough
	case "America/Knox_IN":
		fallthrough
	case "America/Kralendijk":
		fallthrough
	case "America/La_Paz":
		fallthrough
	case "America/Lima":
		fallthrough
	case "America/Los_Angeles":
		fallthrough
	case "America/Louisville":
		fallthrough
	case "America/Lower_Princes":
		fallthrough
	case "America/Maceio":
		fallthrough
	case "America/Managua":
		fallthrough
	case "America/Manaus":
		fallthrough
	case "America/Marigot":
		fallthrough
	case "America/Martinique":
		fallthrough
	case "America/Matamoros":
		fallthrough
	case "America/Mazatlan":
		fallthrough
	case "America/Mendoza":
		fallthrough
	case "America/Menominee":
		fallthrough
	case "America/Merida":
		fallthrough
	case "America/Metlakatla":
		fallthrough
	case "America/Mexico_City":
		fallthrough
	case "America/Miquelon":
		fallthrough
	case "America/Moncton":
		fallthrough
	case "America/Monterrey":
		fallthrough
	case "America/Montevideo":
		fallthrough
	case "America/Montreal":
		fallthrough
	case "America/Montserrat":
		fallthrough
	case "America/Nassau":
		fallthrough
	case "America/New_York":
		fallthrough
	case "America/Nipigon":
		fallthrough
	case "America/Nome":
		fallthrough
	case "America/Noronha":
		fallthrough
	case "America/North_Dakota/Beulah":
		fallthrough
	case "America/North_Dakota/Center":
		fallthrough
	case "America/North_Dakota/New_Salem":
		fallthrough
	case "America/Nuuk":
		fallthrough
	case "America/Ojinaga":
		fallthrough
	case "America/Panama":
		fallthrough
	case "America/Pangnirtung":
		fallthrough
	case "America/Paramaribo":
		fallthrough
	case "America/Phoenix":
		fallthrough
	case "America/Port-au-Prince":
		fallthrough
	case "America/Port_of_Spain":
		fallthrough
	case "America/Porto_Acre":
		fallthrough
	case "America/Porto_Velho":
		fallthrough
	case "America/Puerto_Rico":
		fallthrough
	case "America/Punta_Arenas":
		fallthrough
	case "America/Rainy_River":
		fallthrough
	case "America/Rankin_Inlet":
		fallthrough
	case "America/Recife":
		fallthrough
	case "America/Regina":
		fallthrough
	case "America/Resolute":
		fallthrough
	case "America/Rio_Branco":
		fallthrough
	case "America/Rosario":
		fallthrough
	case "America/Santa_Isabel":
		fallthrough
	case "America/Santarem":
		fallthrough
	case "America/Santiago":
		fallthrough
	case "America/Santo_Domingo":
		fallthrough
	case "America/Sao_Paulo":
		fallthrough
	case "America/Scoresbysund":
		fallthrough
	case "America/Shiprock":
		fallthrough
	case "America/Sitka":
		fallthrough
	case "America/St_Barthelemy":
		fallthrough
	case "America/St_Johns":
		fallthrough
	case "America/St_Kitts":
		fallthrough
	case "America/St_Lucia":
		fallthrough
	case "America/St_Thomas":
		fallthrough
	case "America/St_Vincent":
		fallthrough
	case "America/Swift_Current":
		fallthrough
	case "America/Tegucigalpa":
		fallthrough
	case "America/Thule":
		fallthrough
	case "America/Thunder_Bay":
		fallthrough
	case "America/Tijuana":
		fallthrough
	case "America/Toronto":
		fallthrough
	case "America/Tortola":
		fallthrough
	case "America/Vancouver":
		fallthrough
	case "America/Virgin":
		fallthrough
	case "America/Whitehorse":
		fallthrough
	case "America/Winnipeg":
		fallthrough
	case "America/Yakutat":
		fallthrough
	case "America/Yellowknife":
		fallthrough
	case "Antarctica/Casey":
		fallthrough
	case "Antarctica/Davis":
		fallthrough
	case "Antarctica/DumontDUrville":
		fallthrough
	case "Antarctica/Macquarie":
		fallthrough
	case "Antarctica/Mawson":
		fallthrough
	case "Antarctica/McMurdo":
		fallthrough
	case "Antarctica/Palmer":
		fallthrough
	case "Antarctica/Rothera":
		fallthrough
	case "Antarctica/South_Pole":
		fallthrough
	case "Antarctica/Syowa":
		fallthrough
	case "Antarctica/Troll":
		fallthrough
	case "Antarctica/Vostok":
		fallthrough
	case "Arctic/Longyearbyen":
		fallthrough
	case "Asia/Aden":
		fallthrough
	case "Asia/Almaty":
		fallthrough
	case "Asia/Amman":
		fallthrough
	case "Asia/Anadyr":
		fallthrough
	case "Asia/Aqtau":
		fallthrough
	case "Asia/Aqtobe":
		fallthrough
	case "Asia/Ashgabat":
		fallthrough
	case "Asia/Ashkhabad":
		fallthrough
	case "Asia/Atyrau":
		fallthrough
	case "Asia/Baghdad":
		fallthrough
	case "Asia/Bahrain":
		fallthrough
	case "Asia/Baku":
		fallthrough
	case "Asia/Bangkok":
		fallthrough
	case "Asia/Barnaul":
		fallthrough
	case "Asia/Beirut":
		fallthrough
	case "Asia/Bishkek":
		fallthrough
	case "Asia/Brunei":
		fallthrough
	case "Asia/Calcutta":
		fallthrough
	case "Asia/Chita":
		fallthrough
	case "Asia/Choibalsan":
		fallthrough
	case "Asia/Chongqing":
		fallthrough
	case "Asia/Chungking":
		fallthrough
	case "Asia/Colombo":
		fallthrough
	case "Asia/Dacca":
		fallthrough
	case "Asia/Damascus":
		fallthrough
	case "Asia/Dhaka":
		fallthrough
	case "Asia/Dili":
		fallthrough
	case "Asia/Dubai":
		fallthrough
	case "Asia/Dushanbe":
		fallthrough
	case "Asia/Famagusta":
		fallthrough
	case "Asia/Gaza":
		fallthrough
	case "Asia/Harbin":
		fallthrough
	case "Asia/Hebron":
		fallthrough
	case "Asia/Ho_Chi_Minh":
		fallthrough
	case "Asia/Hong_Kong":
		fallthrough
	case "Asia/Hovd":
		fallthrough
	case "Asia/Irkutsk":
		fallthrough
	case "Asia/Istanbul":
		fallthrough
	case "Asia/Jakarta":
		fallthrough
	case "Asia/Jayapura":
		fallthrough
	case "Asia/Jerusalem":
		fallthrough
	case "Asia/Kabul":
		fallthrough
	case "Asia/Kamchatka":
		fallthrough
	case "Asia/Karachi":
		fallthrough
	case "Asia/Kashgar":
		fallthrough
	case "Asia/Kathmandu":
		fallthrough
	case "Asia/Katmandu":
		fallthrough
	case "Asia/Khandyga":
		fallthrough
	case "Asia/Kolkata":
		fallthrough
	case "Asia/Krasnoyarsk":
		fallthrough
	case "Asia/Kuala_Lumpur":
		fallthrough
	case "Asia/Kuching":
		fallthrough
	case "Asia/Kuwait":
		fallthrough
	case "Asia/Macao":
		fallthrough
	case "Asia/Macau":
		fallthrough
	case "Asia/Magadan":
		fallthrough
	case "Asia/Makassar":
		fallthrough
	case "Asia/Manila":
		fallthrough
	case "Asia/Muscat":
		fallthrough
	case "Asia/Nicosia":
		fallthrough
	case "Asia/Novokuznetsk":
		fallthrough
	case "Asia/Novosibirsk":
		fallthrough
	case "Asia/Omsk":
		fallthrough
	case "Asia/Oral":
		fallthrough
	case "Asia/Phnom_Penh":
		fallthrough
	case "Asia/Pontianak":
		fallthrough
	case "Asia/Pyongyang":
		fallthrough
	case "Asia/Qatar":
		fallthrough
	case "Asia/Qostanay":
		fallthrough
	case "Asia/Qyzylorda":
		fallthrough
	case "Asia/Rangoon":
		fallthrough
	case "Asia/Riyadh":
		fallthrough
	case "Asia/Saigon":
		fallthrough
	case "Asia/Sakhalin":
		fallthrough
	case "Asia/Samarkand":
		fallthrough
	case "Asia/Seoul":
		fallthrough
	case "Asia/Shanghai":
		fallthrough
	case "Asia/Singapore":
		fallthrough
	case "Asia/Srednekolymsk":
		fallthrough
	case "Asia/Taipei":
		fallthrough
	case "Asia/Tashkent":
		fallthrough
	case "Asia/Tbilisi":
		fallthrough
	case "Asia/Tehran":
		fallthrough
	case "Asia/Tel_Aviv":
		fallthrough
	case "Asia/Thimbu":
		fallthrough
	case "Asia/Thimphu":
		fallthrough
	case "Asia/Tokyo":
		fallthrough
	case "Asia/Tomsk":
		fallthrough
	case "Asia/Ujung_Pandang":
		fallthrough
	case "Asia/Ulaanbaatar":
		fallthrough
	case "Asia/Ulan_Bator":
		fallthrough
	case "Asia/Urumqi":
		fallthrough
	case "Asia/Ust-Nera":
		fallthrough
	case "Asia/Vientiane":
		fallthrough
	case "Asia/Vladivostok":
		fallthrough
	case "Asia/Yakutsk":
		fallthrough
	case "Asia/Yangon":
		fallthrough
	case "Asia/Yekaterinburg":
		fallthrough
	case "Asia/Yerevan":
		fallthrough
	case "Atlantic/Azores":
		fallthrough
	case "Atlantic/Bermuda":
		fallthrough
	case "Atlantic/Canary":
		fallthrough
	case "Atlantic/Cape_Verde":
		fallthrough
	case "Atlantic/Faeroe":
		fallthrough
	case "Atlantic/Faroe":
		fallthrough
	case "Atlantic/Jan_Mayen":
		fallthrough
	case "Atlantic/Madeira":
		fallthrough
	case "Atlantic/Reykjavik":
		fallthrough
	case "Atlantic/South_Georgia":
		fallthrough
	case "Atlantic/St_Helena":
		fallthrough
	case "Atlantic/Stanley":
		fallthrough
	case "Australia/ACT":
		fallthrough
	case "Australia/Adelaide":
		fallthrough
	case "Australia/Brisbane":
		fallthrough
	case "Australia/Broken_Hill":
		fallthrough
	case "Australia/Canberra":
		fallthrough
	case "Australia/Currie":
		fallthrough
	case "Australia/Darwin":
		fallthrough
	case "Australia/Eucla":
		fallthrough
	case "Australia/Hobart":
		fallthrough
	case "Australia/LHI":
		fallthrough
	case "Australia/Lindeman":
		fallthrough
	case "Australia/Lord_Howe":
		fallthrough
	case "Australia/Melbourne":
		fallthrough
	case "Australia/NSW":
		fallthrough
	case "Australia/North":
		fallthrough
	case "Australia/Perth":
		fallthrough
	case "Australia/Queensland":
		fallthrough
	case "Australia/South":
		fallthrough
	case "Australia/Sydney":
		fallthrough
	case "Australia/Tasmania":
		fallthrough
	case "Australia/Victoria":
		fallthrough
	case "Australia/West":
		fallthrough
	case "Australia/Yancowinna":
		fallthrough
	case "Brazil/Acre":
		fallthrough
	case "Brazil/DeNoronha":
		fallthrough
	case "Brazil/East":
		fallthrough
	case "Brazil/West":
		fallthrough
	case "CET":
		fallthrough
	case "CST6CDT":
		fallthrough
	case "Canada/Atlantic":
		fallthrough
	case "Canada/Central":
		fallthrough
	case "Canada/Eastern":
		fallthrough
	case "Canada/Mountain":
		fallthrough
	case "Canada/Newfoundland":
		fallthrough
	case "Canada/Pacific":
		fallthrough
	case "Canada/Saskatchewan":
		fallthrough
	case "Canada/Yukon":
		fallthrough
	case "Chile/Continental":
		fallthrough
	case "Chile/EasterIsland":
		fallthrough
	case "Cuba":
		fallthrough
	case "EET":
		fallthrough
	case "EST":
		fallthrough
	case "EST5EDT":
		fallthrough
	case "Egypt":
		fallthrough
	case "Eire":
		fallthrough
	case "Etc/GMT":
		fallthrough
	case "Etc/GMT+0":
		fallthrough
	case "Etc/GMT+1":
		fallthrough
	case "Etc/GMT+10":
		fallthrough
	case "Etc/GMT+11":
		fallthrough
	case "Etc/GMT+12":
		fallthrough
	case "Etc/GMT+2":
		fallthrough
	case "Etc/GMT+3":
		fallthrough
	case "Etc/GMT+4":
		fallthrough
	case "Etc/GMT+5":
		fallthrough
	case "Etc/GMT+6":
		fallthrough
	case "Etc/GMT+7":
		fallthrough
	case "Etc/GMT+8":
		fallthrough
	case "Etc/GMT+9":
		fallthrough
	case "Etc/GMT-0":
		fallthrough
	case "Etc/GMT-1":
		fallthrough
	case "Etc/GMT-10":
		fallthrough
	case "Etc/GMT-11":
		fallthrough
	case "Etc/GMT-12":
		fallthrough
	case "Etc/GMT-13":
		fallthrough
	case "Etc/GMT-14":
		fallthrough
	case "Etc/GMT-2":
		fallthrough
	case "Etc/GMT-3":
		fallthrough
	case "Etc/GMT-4":
		fallthrough
	case "Etc/GMT-5":
		fallthrough
	case "Etc/GMT-6":
		fallthrough
	case "Etc/GMT-7":
		fallthrough
	case "Etc/GMT-8":
		fallthrough
	case "Etc/GMT-9":
		fallthrough
	case "Etc/Greenwich":
		fallthrough
	case "Etc/UCT":
		fallthrough
	case "Etc/UTC":
		fallthrough
	case "Etc/Universal":
		fallthrough
	case "Etc/Zulu":
		fallthrough
	case "Europe/Amsterdam":
		fallthrough
	case "Europe/Andorra":
		fallthrough
	case "Europe/Astrakhan":
		fallthrough
	case "Europe/Athens":
		fallthrough
	case "Europe/Belfast":
		fallthrough
	case "Europe/Belgrade":
		fallthrough
	case "Europe/Berlin":
		fallthrough
	case "Europe/Bratislava":
		fallthrough
	case "Europe/Brussels":
		fallthrough
	case "Europe/Bucharest":
		fallthrough
	case "Europe/Budapest":
		fallthrough
	case "Europe/Busingen":
		fallthrough
	case "Europe/Chisinau":
		fallthrough
	case "Europe/Copenhagen":
		fallthrough
	case "Europe/Dublin":
		fallthrough
	case "Europe/Gibraltar":
		fallthrough
	case "Europe/Guernsey":
		fallthrough
	case "Europe/Helsinki":
		fallthrough
	case "Europe/Isle_of_Man":
		fallthrough
	case "Europe/Istanbul":
		fallthrough
	case "Europe/Jersey":
		fallthrough
	case "Europe/Kaliningrad":
		fallthrough
	case "Europe/Kiev":
		fallthrough
	case "Europe/Kirov":
		fallthrough
	case "Europe/Lisbon":
		fallthrough
	case "Europe/Ljubljana":
		fallthrough
	case "Europe/London":
		fallthrough
	case "Europe/Luxembourg":
		fallthrough
	case "Europe/Madrid":
		fallthrough
	case "Europe/Malta":
		fallthrough
	case "Europe/Mariehamn":
		fallthrough
	case "Europe/Minsk":
		fallthrough
	case "Europe/Monaco":
		fallthrough
	case "Europe/Moscow":
		fallthrough
	case "Europe/Nicosia":
		fallthrough
	case "Europe/Oslo":
		fallthrough
	case "Europe/Paris":
		fallthrough
	case "Europe/Podgorica":
		fallthrough
	case "Europe/Prague":
		fallthrough
	case "Europe/Riga":
		fallthrough
	case "Europe/Rome":
		fallthrough
	case "Europe/Samara":
		fallthrough
	case "Europe/San_Marino":
		fallthrough
	case "Europe/Sarajevo":
		fallthrough
	case "Europe/Saratov":
		fallthrough
	case "Europe/Simferopol":
		fallthrough
	case "Europe/Skopje":
		fallthrough
	case "Europe/Sofia":
		fallthrough
	case "Europe/Stockholm":
		fallthrough
	case "Europe/Tallinn":
		fallthrough
	case "Europe/Tirane":
		fallthrough
	case "Europe/Tiraspol":
		fallthrough
	case "Europe/Ulyanovsk":
		fallthrough
	case "Europe/Uzhgorod":
		fallthrough
	case "Europe/Vaduz":
		fallthrough
	case "Europe/Vatican":
		fallthrough
	case "Europe/Vienna":
		fallthrough
	case "Europe/Vilnius":
		fallthrough
	case "Europe/Volgograd":
		fallthrough
	case "Europe/Warsaw":
		fallthrough
	case "Europe/Zagreb":
		fallthrough
	case "Europe/Zaporozhye":
		fallthrough
	case "Europe/Zurich":
		fallthrough
	case "GB":
		fallthrough
	case "GB-Eire":
		fallthrough
	case "GMT":
		fallthrough
	case "GMT+0":
		fallthrough
	case "GMT-0":
		fallthrough
	case "Greenwich":
		fallthrough
	case "HST":
		fallthrough
	case "Hongkong":
		fallthrough
	case "Iceland":
		fallthrough
	case "Indian/Antananarivo":
		fallthrough
	case "Indian/Chagos":
		fallthrough
	case "Indian/Christmas":
		fallthrough
	case "Indian/Cocos":
		fallthrough
	case "Indian/Comoro":
		fallthrough
	case "Indian/Kerguelen":
		fallthrough
	case "Indian/Mahe":
		fallthrough
	case "Indian/Maldives":
		fallthrough
	case "Indian/Mauritius":
		fallthrough
	case "Indian/Mayotte":
		fallthrough
	case "Indian/Reunion":
		fallthrough
	case "Iran":
		fallthrough
	case "Israel":
		fallthrough
	case "Jamaica":
		fallthrough
	case "Japan":
		fallthrough
	case "Kwajalein":
		fallthrough
	case "Libya":
		fallthrough
	case "MET":
		fallthrough
	case "MST":
		fallthrough
	case "MST7MDT":
		fallthrough
	case "Mexico/BajaNorte":
		fallthrough
	case "Mexico/BajaSur":
		fallthrough
	case "Mexico/General":
		fallthrough
	case "NZ":
		fallthrough
	case "NZ-CHAT":
		fallthrough
	case "Navajo":
		fallthrough
	case "PRC":
		fallthrough
	case "PST8PDT":
		fallthrough
	case "Pacific/Apia":
		fallthrough
	case "Pacific/Auckland":
		fallthrough
	case "Pacific/Bougainville":
		fallthrough
	case "Pacific/Chatham":
		fallthrough
	case "Pacific/Chuuk":
		fallthrough
	case "Pacific/Easter":
		fallthrough
	case "Pacific/Efate":
		fallthrough
	case "Pacific/Enderbury":
		fallthrough
	case "Pacific/Fakaofo":
		fallthrough
	case "Pacific/Fiji":
		fallthrough
	case "Pacific/Funafuti":
		fallthrough
	case "Pacific/Galapagos":
		fallthrough
	case "Pacific/Gambier":
		fallthrough
	case "Pacific/Guadalcanal":
		fallthrough
	case "Pacific/Guam":
		fallthrough
	case "Pacific/Honolulu":
		fallthrough
	case "Pacific/Johnston":
		fallthrough
	case "Pacific/Kanton":
		fallthrough
	case "Pacific/Kiritimati":
		fallthrough
	case "Pacific/Kosrae":
		fallthrough
	case "Pacific/Kwajalein":
		fallthrough
	case "Pacific/Majuro":
		fallthrough
	case "Pacific/Marquesas":
		fallthrough
	case "Pacific/Midway":
		fallthrough
	case "Pacific/Nauru":
		fallthrough
	case "Pacific/Niue":
		fallthrough
	case "Pacific/Norfolk":
		fallthrough
	case "Pacific/Noumea":
		fallthrough
	case "Pacific/Pago_Pago":
		fallthrough
	case "Pacific/Palau":
		fallthrough
	case "Pacific/Pitcairn":
		fallthrough
	case "Pacific/Pohnpei":
		fallthrough
	case "Pacific/Ponape":
		fallthrough
	case "Pacific/Port_Moresby":
		fallthrough
	case "Pacific/Rarotonga":
		fallthrough
	case "Pacific/Saipan":
		fallthrough
	case "Pacific/Samoa":
		fallthrough
	case "Pacific/Tahiti":
		fallthrough
	case "Pacific/Tarawa":
		fallthrough
	case "Pacific/Tongatapu":
		fallthrough
	case "Pacific/Truk":
		fallthrough
	case "Pacific/Wake":
		fallthrough
	case "Pacific/Wallis":
		fallthrough
	case "Pacific/Yap":
		fallthrough
	case "Poland":
		fallthrough
	case "Portugal":
		fallthrough
	case "ROC":
		fallthrough
	case "ROK":
		fallthrough
	case "Singapore":
		fallthrough
	case "Turkey":
		fallthrough
	case "UCT":
		fallthrough
	case "US/Alaska":
		fallthrough
	case "US/Aleutian":
		fallthrough
	case "US/Arizona":
		fallthrough
	case "US/Central":
		fallthrough
	case "US/East-Indiana":
		fallthrough
	case "US/Eastern":
		fallthrough
	case "US/Hawaii":
		fallthrough
	case "US/Indiana-Starke":
		fallthrough
	case "US/Michigan":
		fallthrough
	case "US/Mountain":
		fallthrough
	case "US/Pacific":
		fallthrough
	case "US/Samoa":
		fallthrough
	case "UTC":
		fallthrough
	case "Universal":
		fallthrough
	case "W-SU":
		fallthrough
	case "WET":
		fallthrough
	case "Zulu":
		*e = TimezoneEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TimezoneEnum: %v", v)
	}
}
