// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type UnitInput struct {
	ApprovalCurrencyLimit *string `json:"approval_currency_limit,omitempty" form:"name=approval_currency_limit" multipartForm:"name=approval_currency_limit"`
	CurrentResidents      []int64 `json:"current_residents,omitempty" form:"name=current_residents" multipartForm:"name=current_residents"`
	MaintenanceNotes      *string `json:"maintenance_notes,omitempty" form:"name=maintenance_notes" multipartForm:"name=maintenance_notes"`
	PropertyID            int64   `json:"property_id" form:"name=property_id" multipartForm:"name=property_id"`
	// This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302
	Unit        *string  `json:"unit,omitempty" form:"name=unit" multipartForm:"name=unit"`
	UnitAddress *Address `json:"unit_address,omitempty" form:"name=unit_address,json" multipartForm:"name=unit_address,json"`
}

type Unit struct {
	ApprovalCurrencyLimit *string   `json:"approval_currency_limit,omitempty"`
	Created               time.Time `json:"created"`
	CurrentResidents      []int64   `json:"current_residents,omitempty"`
	ID                    int64     `json:"id"`
	IsActive              bool      `json:"is_active"`
	MaintenanceNotes      *string   `json:"maintenance_notes,omitempty"`
	PropertyID            int64     `json:"property_id"`
	// This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302
	Unit        *string   `json:"unit,omitempty"`
	UnitAddress *Address  `json:"unit_address,omitempty"`
	Updated     time.Time `json:"updated"`
}
