// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VendorInvite struct {
	CompanyName  *string `json:"company_name,omitempty" form:"name=company_name" multipartForm:"name=company_name"`
	CompanyPhone *string `json:"company_phone,omitempty" form:"name=company_phone" multipartForm:"name=company_phone"`
	Email        string  `json:"email" form:"name=email" multipartForm:"name=email"`
	FirstName    *string `json:"first_name,omitempty" form:"name=first_name" multipartForm:"name=first_name"`
	LastName     *string `json:"last_name,omitempty" form:"name=last_name" multipartForm:"name=last_name"`
	Line1        *string `json:"line_1,omitempty" form:"name=line_1" multipartForm:"name=line_1"`
	Postcode     *string `json:"postcode,omitempty" form:"name=postcode" multipartForm:"name=postcode"`
}
