// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Vendor struct {
	Address                Address   `json:"address"`
	Created                time.Time `json:"created"`
	Email                  *string   `json:"email,omitempty"`
	ExcludedPropertyGroups []int64   `json:"excluded_property_groups"`
	// Home phone number. Must be in E.164 format, e.g. '+14155552671'.
	Fax      *string `json:"fax,omitempty"`
	ID       int64   `json:"id"`
	IsActive bool    `json:"is_active"`
	Name     *string `json:"name,omitempty"`
	// Home phone number. Must be in E.164 format, e.g. '+14155552671'.
	Phone   *string   `json:"phone,omitempty"`
	Updated time.Time `json:"updated"`
}
