// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type VendorAvailabilitySegment struct {
	AssignmentRequest  int64                  `json:"assignment_request"`
	CreateBy           map[string]interface{} `json:"create_by,omitempty"`
	Created            time.Time              `json:"created"`
	Event              BaseEvent              `json:"event"`
	Expired            *bool                  `json:"expired,omitempty"`
	ID                 int64                  `json:"id"`
	RemindersScheduled *bool                  `json:"reminders_scheduled,omitempty"`
	UpdateBy           map[string]interface{} `json:"update_by,omitempty"`
	Updated            time.Time              `json:"updated"`
}
