// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type VendorAssignmentRequest struct {
	AcceptBy                 *time.Time             `json:"accept_by,omitempty"`
	Accepted                 *time.Time             `json:"accepted,omitempty"`
	Canceled                 *time.Time             `json:"canceled,omitempty"`
	CreateBy                 map[string]interface{} `json:"create_by,omitempty"`
	Created                  time.Time              `json:"created"`
	ID                       int64                  `json:"id"`
	Meld                     int64                  `json:"meld"`
	PreferenceListAssignment *int64                 `json:"preference_list_assignment,omitempty"`
	RejectReason             *string                `json:"reject_reason,omitempty"`
	Rejected                 *time.Time             `json:"rejected,omitempty"`
	UpdateBy                 map[string]interface{} `json:"update_by,omitempty"`
	Updated                  time.Time              `json:"updated"`
	Vendor                   MeldListViewVendor     `json:"vendor"`
}
