// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WorkEntrySerializerList struct {
	Agent           int64      `json:"agent"`
	Checkin         *time.Time `json:"checkin,omitempty"`
	Checkout        *time.Time `json:"checkout,omitempty"`
	Created         time.Time  `json:"created"`
	Description     *string    `json:"description,omitempty"`
	Hours           *float32   `json:"hours,omitempty"`
	ID              int64      `json:"id"`
	LongDescription *string    `json:"long_description,omitempty"`
	Meld            int64      `json:"meld"`
	Updated         time.Time  `json:"updated"`
	Updater         int64      `json:"updater"`
}
