// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type WorkCategoryEnum string

const (
	WorkCategoryEnumForRentSign              WorkCategoryEnum = "FOR_RENT_SIGN"
	WorkCategoryEnumEvaluation               WorkCategoryEnum = "EVALUATION"
	WorkCategoryEnumTurnover                 WorkCategoryEnum = "TURNOVER"
	WorkCategoryEnumAppliances               WorkCategoryEnum = "APPLIANCES"
	WorkCategoryEnumBlindsWindowTreatments   WorkCategoryEnum = "BLINDS_WINDOW_TREATMENTS"
	WorkCategoryEnumCircuitBreaker           WorkCategoryEnum = "CIRCUIT_BREAKER"
	WorkCategoryEnumCleaning                 WorkCategoryEnum = "CLEANING"
	WorkCategoryEnumDoors                    WorkCategoryEnum = "DOORS"
	WorkCategoryEnumDriveway                 WorkCategoryEnum = "DRIVEWAY"
	WorkCategoryEnumDrywall                  WorkCategoryEnum = "DRYWALL"
	WorkCategoryEnumElectrical               WorkCategoryEnum = "ELECTRICAL"
	WorkCategoryEnumExterior                 WorkCategoryEnum = "EXTERIOR"
	WorkCategoryEnumFireplace                WorkCategoryEnum = "FIREPLACE"
	WorkCategoryEnumFlooring                 WorkCategoryEnum = "FLOORING"
	WorkCategoryEnumGarageDoor               WorkCategoryEnum = "GARAGE_DOOR"
	WorkCategoryEnumGarbageDisposal          WorkCategoryEnum = "GARBAGE_DISPOSAL"
	WorkCategoryEnumGeneral                  WorkCategoryEnum = "GENERAL"
	WorkCategoryEnumHardware                 WorkCategoryEnum = "HARDWARE"
	WorkCategoryEnumHvac                     WorkCategoryEnum = "HVAC"
	WorkCategoryEnumInterior                 WorkCategoryEnum = "INTERIOR"
	WorkCategoryEnumLandscaping              WorkCategoryEnum = "LANDSCAPING"
	WorkCategoryEnumLocks                    WorkCategoryEnum = "LOCKS"
	WorkCategoryEnumOtherWorkCategory        WorkCategoryEnum = "OTHER_WORK_CATEGORY"
	WorkCategoryEnumPainting                 WorkCategoryEnum = "PAINTING"
	WorkCategoryEnumOutsideWaterSpigot       WorkCategoryEnum = "OUTSIDE_WATER_SPIGOT"
	WorkCategoryEnumPestControl              WorkCategoryEnum = "PEST_CONTROL"
	WorkCategoryEnumPlumbing                 WorkCategoryEnum = "PLUMBING"
	WorkCategoryEnumCarpentry                WorkCategoryEnum = "CARPENTRY"
	WorkCategoryEnumPool                     WorkCategoryEnum = "POOL"
	WorkCategoryEnumRoofing                  WorkCategoryEnum = "ROOFING"
	WorkCategoryEnumSewer                    WorkCategoryEnum = "SEWER"
	WorkCategoryEnumShower                   WorkCategoryEnum = "SHOWER"
	WorkCategoryEnumSiding                   WorkCategoryEnum = "SIDING"
	WorkCategoryEnumSmokeDetectorCoDetectors WorkCategoryEnum = "SMOKE_DETECTOR_CO_DETECTORS"
	WorkCategoryEnumSoffitFascia             WorkCategoryEnum = "SOFFIT_FASCIA"
	WorkCategoryEnumStairs                   WorkCategoryEnum = "STAIRS"
	WorkCategoryEnumToilet                   WorkCategoryEnum = "TOILET"
	WorkCategoryEnumTowelBars                WorkCategoryEnum = "TOWEL_BARS"
	WorkCategoryEnumViolations               WorkCategoryEnum = "VIOLATIONS"
	WorkCategoryEnumWasherDryer              WorkCategoryEnum = "WASHER_DRYER"
	WorkCategoryEnumWaterDamage              WorkCategoryEnum = "WATER_DAMAGE"
	WorkCategoryEnumWaterHeater              WorkCategoryEnum = "WATER_HEATER"
	WorkCategoryEnumWaterSoftener            WorkCategoryEnum = "WATER_SOFTENER"
	WorkCategoryEnumWindows                  WorkCategoryEnum = "WINDOWS"
)

func (e WorkCategoryEnum) ToPointer() *WorkCategoryEnum {
	return &e
}

func (e *WorkCategoryEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FOR_RENT_SIGN":
		fallthrough
	case "EVALUATION":
		fallthrough
	case "TURNOVER":
		fallthrough
	case "APPLIANCES":
		fallthrough
	case "BLINDS_WINDOW_TREATMENTS":
		fallthrough
	case "CIRCUIT_BREAKER":
		fallthrough
	case "CLEANING":
		fallthrough
	case "DOORS":
		fallthrough
	case "DRIVEWAY":
		fallthrough
	case "DRYWALL":
		fallthrough
	case "ELECTRICAL":
		fallthrough
	case "EXTERIOR":
		fallthrough
	case "FIREPLACE":
		fallthrough
	case "FLOORING":
		fallthrough
	case "GARAGE_DOOR":
		fallthrough
	case "GARBAGE_DISPOSAL":
		fallthrough
	case "GENERAL":
		fallthrough
	case "HARDWARE":
		fallthrough
	case "HVAC":
		fallthrough
	case "INTERIOR":
		fallthrough
	case "LANDSCAPING":
		fallthrough
	case "LOCKS":
		fallthrough
	case "OTHER_WORK_CATEGORY":
		fallthrough
	case "PAINTING":
		fallthrough
	case "OUTSIDE_WATER_SPIGOT":
		fallthrough
	case "PEST_CONTROL":
		fallthrough
	case "PLUMBING":
		fallthrough
	case "CARPENTRY":
		fallthrough
	case "POOL":
		fallthrough
	case "ROOFING":
		fallthrough
	case "SEWER":
		fallthrough
	case "SHOWER":
		fallthrough
	case "SIDING":
		fallthrough
	case "SMOKE_DETECTOR_CO_DETECTORS":
		fallthrough
	case "SOFFIT_FASCIA":
		fallthrough
	case "STAIRS":
		fallthrough
	case "TOILET":
		fallthrough
	case "TOWEL_BARS":
		fallthrough
	case "VIOLATIONS":
		fallthrough
	case "WASHER_DRYER":
		fallthrough
	case "WATER_DAMAGE":
		fallthrough
	case "WATER_HEATER":
		fallthrough
	case "WATER_SOFTENER":
		fallthrough
	case "WINDOWS":
		*e = WorkCategoryEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkCategoryEnum: %v", v)
	}
}
