// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WriteableTag struct {
	CreateBy   map[string]interface{} `json:"create_by,omitempty"`
	Created    time.Time              `json:"created"`
	ID         int64                  `json:"id"`
	Management int64                  `json:"management"`
	Name       string                 `json:"name"`
	UpdateBy   map[string]interface{} `json:"update_by,omitempty"`
	Updated    time.Time              `json:"updated"`
}
